### ISSUE TITLE
Serialization of an object with unknown attributes

### ISSUE THREAD

**Issue by smartiniOnGitHub** [fastify/fast-json-stringify#108]
Hi all, sorry this is a question and not an issue ... in a library I'm writing [fastify-cloudevents](https://github.com/smartiniOnGitHub/fastify-cloudevents), I need to serialize even an object 'data' (usually it's an object, but could be even a Map or a Set ... and with the if/then/else jsonschema feature I should be able to handle it, ok), anyway data is an object provided by consumers of the library, so I can't define more in detail its structure in the schema ... and in this way if I serialize in JSON I only get an empty object, so the solution seems to enable the additionalProperties flag, right ?
But in this case is there a way for me to let the schema handle only attributes of the 'data' object (and filter out other attributes maybe present in the main data structure), like some kind of 'allow-nested-properties' but not other 'top-level-properties' ?
Hope to explain my problem well ... otherwise I can provide more details; note that current code in my repo show the behavior.
Thanks a lot for now, Sandro

**Comment by mcollina** [comment]
Unfortunately it's not clear. Can you make an example?

**Comment by smartiniOnGitHub** [comment]
Sure, in the library I configure a generic schema for serializing objects in json, see [here](https://github.com/smartiniOnGitHub/fastify-cloudevents/blob/master/cloudevent.js#L189); but as you can see, the 'data' attribute is not known because consumers of the library will fill it, so in the json schema I define it as a generic 'object'.
So in the test (using TAP) shown [here](https://github.com/smartiniOnGitHub/fastify-cloudevents/blob/master/test/cloudevents-serialization.test.js), that object is serialized as an empty object even if it contains some attribute.
So I guess if/how it would it be possible to keep it defined as object and let fast-json-stringify handle its properties ... otherwise I think I could enable the additionalProperties flag, right ?
Or for better performance maybe I could ask to (my) library consumers to pass the structure of that 'data' attribute, but different events will have different data objects inside, so I'm not sure this would be the best approach ...
What do you think ?
Thanks a lot.

**Comment by mcollina** [comment]
You should use `additionalProperties: true`  in there. You could also ask your users to specify their schema, but I think `additionalProperties: true` is a better user experience.

**Comment by smartiniOnGitHub** [comment]
ok, thank you very much for the info.
