### ISSUE TITLE
Run JSON-schema test-suite

### ISSUE THREAD

**Issue by StarpTech** [fastify/fast-json-stringify#113]
Hi, while we support many features we should still track which JSON-Schema features are covered right now. We should add the official JSON-schema tests-suite as a submodule and write against it. In that way, we can create TODO what's is missing and motivate people to fulfill it.

Node branch: https://github.com/json-schema-org/JSON-Schema-Test-Suite/tree/node
Up-to-date: https://github.com/json-schema-org/JSON-Schema-Test-Suite

**Comment by mcollina** [comment]
This would be fantastic!

**Comment by allevo** [comment]
I'm 👍  absolutely. We had to study how to integrare their tests here: the validation tests work contrariwise.

**Comment by StarpTech** [comment]
Ticket can be closed. The JSON-schema test suite was merged with https://github.com/fastify/fast-json-stringify/pull/122
