### ISSUE TITLE
\d in patternproperties seems to not work

### ISSUE THREAD

**Issue by honestserpent** [fastify/fast-json-stringify#114]
Hi, I have an object whose keys represents date in the format _YYYY-MM-DD_ and I am trying to build a schema that matches it, but without any result. It looks like.

```javascript
const fastJson = require('fast-json-stringify')
const stringify = fastJson({
  title: 'RabbitMQ Message',
  type: 'object',
  patternProperties: {
    '^\d{4}-\d{2}-\d{2}$': {
      type: 'string'
    }
  }
})

console.log(stringify({
  '2018-01-01': "foo",
}))
```

returns `{}`.

Using `'^[0-9]{4}-[0-9]{2}-[0-9]{2}$'`works, instead

**Comment by StarpTech** [comment]
Did you try `^\\d{4}-\\d{2}-\\d{2}$` 😄

**Comment by honestserpent** [comment]
Oh Boy.
