### ISSUE TITLE
Allowing the use of a modified Ajv instance

### ISSUE THREAD

**Issue by g-corneu** [fastify/fast-json-stringify#115]
Hi, thanks for all the great work!

I'm having a bit of a problem with reusing a schema in Fastify in the response that has a custom format and as I read the code I tracked it down (I think) to the fact Fastify uses this package to compile the response schemas, but since this package uses an internal instance of Ajv it does not have the custom format.

I'm wondering if you'd be open to a PR that would allow you to specify an instance of Ajv to use?

**Comment by mcollina** [comment]
Thanks for reporting! Would you mind to share an example of what it is not working for you?

**Comment by g-corneu** [comment]
Sure! Here's an exmaple:

```javascript
const ajv = require("ajv")();
const server = require("fastify")();

ajv.setFormat("test", /[a-z]{24}/);

server.setSchemaCompiler(schema => ajv.compile(schema));

server.post("/", {
  schema: {
    response: {
      "200": {
        type: "object";
        properties: {
          test: {
            type: "string",
            format: "test"
          }
        }
      }
    }
  }
}, async (req, res) => ({}));

server.listen();
```

Results in an error similar to:
![screen shot 2018-09-14 at 09 48 22](https://user-images.githubusercontent.com/21124794/45540077-6a24a800-b803-11e8-8647-1bd6e4f2c13b.png)

I realise that it would have made more sense to open this on the main Fastify repository first, apologies! But as I was reading the code for Fastify I (think) I tracked it down to the fact that it uses this package to compile the response schemas.

**Comment by mcollina** [comment]
The problem is that this module _is not used to validate the responses_ before sending them. It is used to render them. As such, it does not know anything about your format, it would in fact be _totally ignored_ even if you pass it through. We use AJV to validate that your schema is valid JSON schema.

Passing in a custom AJV would remove the error, but it will just make that ignored.

**Comment by g-corneu** [comment]
That makes sense, and I don't want any validation, I'd just like to be able to use a schema that I use in both the request and response (because they share the same data) but have the custom format ignored when it is used in the response.

I've realised that there is an alternative to passing in a custom Ajv instance but instead use the option `unknownFormats: "ignore"` instead which would allow custom formats in the response schema but ignore them.

**Comment by mcollina** [comment]
> I've realised that there is an alternative to passing in a custom Ajv instance but instead use the option unknownFormats: "ignore" instead which would allow custom formats in the response schema but ignore them.

I think we should add this to fast-json-stringify ajv config.
