### ISSUE TITLE
Support for toJSON

### ISSUE THREAD

**Issue by sarneeh** [fastify/fast-json-stringify#118]
I'd like to have a little different model structure internally in my app than returning it externally via API. Unfortunately, using `fastify` and `fast-json-stringify` this can't be done as `fast-json-stringify` does not use the objects `toJSON` function to map the data somehow.

I guess it could be on purpose to improve the performance, but this is a little bit unintuitive to do: 

`reply.send(model.toJSON());`

and what even worse:

```js
const models = [arrayOfModels];
reply.send(models.map(model => model.toJSON()));
```

This doesn't make much sense as there's no difference if I have to do this manually or if it would be done by `fast-json-stringify` - just as I'd expect.

Here's a little reproduction:

```js
const fastJson = require("fast-json-stringify");

const stringify = fastJson({
    type: "object",
    properties: {
        groups: {
            type: "array",
            items: {
                type: "string"
            }
        }
    }
});

class User {
    constructor() {
        this.groups = [{ name: "admin" }, { name: "subscriber" }];
    }

    toJSON() {
        return {
            ...this,
            groups: this.groups.map(group => group.name)
        };
    }
}

const user = new User();

console.log(stringify(user)); // returns: {"groups":["[object Object]","[object Object]"]}
console.log(JSON.stringify(user)); // returns: {"groups":["admin","subscriber"]}
```

Could you somehow relate to this issue? And maybe you have some idea for a solution in `fastify`?

**Comment by mcollina** [comment]
If it is not too costly perf-wise, we should check if an object has a toJSON method, and call that before applying the schema. Would you like to send a PR that does that?

**Comment by cemremengu** [comment]
@sarneeh Yes we even pushed the same second. Sorry it's my bad I was just lurking around and saw this, I should have asked first.  It is your right to have this PR 😄

**Comment by sarneeh** [comment]
@cemremengu No problem 😄 I needed some time to find out what's going on in this project. I hope I didn't mess this up completely 😄

**Comment by cemremengu** [comment]
@sarneeh I will close mine in favor of yours and we can continue work from there

**Comment by sarneeh** [comment]
@mcollina Awesome, thank you for the fast publish 🎉

**Comment by mcollina** [comment]
Glad to help! Keep sending PRs :).
