### ISSUE TITLE
anyOf coercion

### ISSUE THREAD

**Issue by Marsup** [fastify/fast-json-stringify#126]
Hi!

I'm trying to understand whether what I see is a bug or an expected behavior. String coercion doesn't seem to happen when inside an `anyOf` (see https://runkit.com/embed/1aoibrghntr5), so my question is should it and if not is there any way to do it?

Thanks!

**Comment by mcollina** [comment]
The way `anyOf` is implemented, we use AJV to validate which one to pick. I think it's a matter of changing Ajv defaults to actually coerce the output. Would you like to send a PR?

**Comment by mcollina** [comment]
Fixed in https://github.com/fastify/fast-json-stringify/pull/150
