### ISSUE TITLE
minProperties is not respected

### ISSUE THREAD

**Issue by romansavchenko** [fastify/fast-json-stringify#132]
minProperties is usually used to not allow empty objects. 
I'm seeing this behavior fail. 

```
 'use strict'

const test = require('tap').test
const build = require('..')

test('minProperties', (t) => {
  t.plan(1)

  const stringify = build({
    title: 'object with missing values',
    type: 'object',
    minProperties: 1,
    properties: {
      shouldNotBeReturned: {
        type: 'object',
        properties: {
          str: {
            type: 'string'
          }
        }
      }
    }
  })

  t.equal('{}', stringify({ shouldNotBeReturned: {} }))
})

```

It returns `{ "shouldNotBeReturned": {} }` instead of the expected `{}`
`{ "shouldNotBeReturned": {} }` is invalid per the schema

**Comment by mcollina** [comment]
I'm kind of lost on why you expect this type of output. Can you please articulate more?

**Comment by romansavchenko** [comment]
As far as I understand currently anything that fails json schema validation is not returned right?
Like if I had "additionalProperties"=false, anything not in the schema would not be returned.

```
const stringify = build({
    type: 'object',
    additionalProperties: false,
    properties: {
      a: {
        type: 'string'
      }
    }
  })

  t.equal('{}', stringify({ 'c': 'b' }))
```

**Comment by mcollina** [comment]
Considering our code, I think the best approach would be to throw if `minProperties` is not respected. I don't think there is any other way that would be performant. Would you like to send a PR?

**Comment by romansavchenko** [comment]
I kind of feel like we should leave it as is, and say additionalProperties is a special case. 

If we throw for minProperties we  should probably throw for all schema failures like (enum, minLength, maxLength, etc.)
Throwing for everthing however, seems less useful since our goal is to stringily fast not necessarily validate the schema.

**Comment by mcollina** [comment]
would you like to send a PR to amend the docs mentioning `additionalProperties` is a special case?

**Comment by romansavchenko** [comment]
Sure.

**Comment by mcollina** [comment]
yes

**Comment by romansavchenko** [comment]
Updated docs https://github.com/fastify/fast-json-stringify/pull/135
