### ISSUE TITLE
Maximum call stack size exceeded when $ref plain name fragment

### ISSUE THREAD

**Issue by Eomm** [fastify/fast-json-stringify#136]
Hi all,
writing this PR https://github.com/fastify/fastify/pull/1425, with the suggestion of Collina, I found that the `$ref` property doesn't support the URI that points to `$id` (alias plain name fragment format).

I write this test that should pass:

```
test('ref internal - plain name fragment', (t) => {
  t.plan(2)

  const schema = {
    title: 'object with $ref',
    definitions: {
      def: {
        $id: '#uri',
        type: 'object',
        properties: {
          str: {
            type: 'string'
          }
        },
        required: ['str']
      }
    },
    type: 'object',
    properties: {
      obj: {
        $ref: '#uri'
      }
    }
  }

  const object = {
    obj: {
      str: 'test'
    }
  }

  const stringify = build(schema)
  const output = stringify(object)

  try {
    JSON.parse(output)
    t.pass()
  } catch (e) {
    t.fail()
  }

  t.equal(output, '{"obj":{"str":"test"}}')
})
```

Double check with AJV, where it works as expected:

```
var Ajv = require('ajv')
var ajv = new Ajv({ allErrors: true }) // options can be passed, e.g. {allErrors: true}

const schema = {
  title: 'object with $ref',
  definitions: {
    def: {
      $id: '#uri',
      type: 'object',
      properties: {
        str: {
          type: 'string'
        }
      },
      required: ['str']
    }
  },
  type: 'object',
  properties: {
    obj: {
      $ref: '#uri'
    }
  }
}

const data = {
  obj: {
    str: 'test'
  }
}

var validate = ajv.compile(schema)
var valid = validate(data)
console.log(valid)
console.log(validate.errors)

```

I'm working on this if it is ok for you 👍
Any suggestion is welcome 😃

**Comment by mcollina** [comment]
Ping us if you are stuck anyhow or if you have questions!

**Comment by Eomm** [comment]
> Ping us if you are stuck anyhow or if you have questions!

I would like to know why this:

https://github.com/fastify/fast-json-stringify/blob/321bc3fb3b1a6896c57a4e5675958a3942d9a880/index.js#L442

(which output `code = return schema[param][param2][param_n]` )
is preferred instead of a recursive code to walk the schema object?

And I'm wondering if should I follow this pattern also in my PR?

Thanks
