### ISSUE TITLE
Be more verbose on schema validation.

### ISSUE THREAD

**Issue by SkeLLLa** [fastify/fast-json-stringify#139]
In Fastify when some schema is not valid it's almost impossible to guess which one. So in order to make it clear error should have schema `key` somewhere.

My suggestion is to wrap https://github.com/fastify/fast-json-stringify/blob/master/index.js#L937 in `try..catch`:

```js
Object.keys(externalSchema).forEach((key) => {
  try {
    ajv.addSchema(externalSchema[key], key);
  } catch (err) {
    err.message = `${key}: ${err.message}`;
    // or create custom error
    throw err;
  }
});
```

**Comment by mcollina** [comment]
Would you like to send a PR to fix this?
