### ISSUE TITLE
Nullable string serialized as double-quoted empty string

### ISSUE THREAD

**Issue by gendronb** [fastify/fast-json-stringify#152]
### Expected Behavior
As mentionned in the docs (https://github.com/fastify/fast-json-stringify#nullable), properties marked as `nullable: true` should be serialized as `null`.

### Current Behavior
Currently, a null string is serialized as a double-quoted empty string (```""```)

### Steps to Reproduce
```js
const fastJson = require('fast-json-stringify')

let stringify = fastJson({
  type: 'object',
  properties: {
    nullableString: { type: 'string', nullable: true },
  }
})

let data = {
  nullableString: null
}

console.log(stringify(data))

// => {"nullableString":""}
```

### Workaround
Remove `nullable: true`  and mark property type as `['string', 'null']`

### Context (Environment)
- node v11.5.0
- fast-json-stringify v1.11.3

**Comment by mcollina** [comment]
Would you like to send a PR to fix this?

**Comment by gendronb** [comment]
@mcollina as mentionned, I have a workaround, but looking into the code, I don't see any solution, everything looks great.

BTW, it also happens with other types (integers, ...)

**Comment by gendronb** [comment]
Just forked the repo, will have a closer look, stay tuned...

**Comment by gendronb** [comment]
@mcollina some progress today, made it to work with integers, numbers, strings, booleans, objects, arrays, but still have to check if it works with nested properties (in arrays or objects)...

**Comment by Eomm** [comment]
Yes, as you said this behaviour is [documented](https://github.com/fastify/fast-json-stringify#nullable), and your workaround is compliant to the JSON-schema standard.

How do you have designed this feature? Is it optional for the user?

**Comment by gendronb** [comment]
@Eomm the way I did it is completely optional. If the `nullable` property is present AND `true`, and the value is `null`, the serialized value will be `null`. Otherwise, the normal serialization process applies...

For example, see this code snippet for strings : 

BEFORE
```js
    case 'string':
      code += `
        json += $asString(obj${accessor})
      `
      break
```


AFTER
```js
   var nullable = schema.nullable === true
    ...
    case 'string':
      code += `
        json += obj${accessor} === null && ${nullable} ? null : $asString(obj${accessor})
      `
      break
```

How does it look to you?

**Comment by gendronb** [comment]
For arrays, the logic is implemented in the `buildArray` method.

For objects, this was the default behavior...

**Comment by Eomm** [comment]
> How does it look to you?

I need to study it a bit 💪

**Comment by adrai** [comment]
Can it be that `nullable: true` does not work if `type: string` and a `format` or `pattern` exists?

**Comment by adrai** [comment]
Seems this is too complex to handle => https://github.com/epoberezkin/ajv/issues/919
