### ISSUE TITLE
data validation 

### ISSUE THREAD

**Issue by matth-c3** [fastify/fast-json-stringify#154]
Hello, 

Would it be possible to add custom function to validate the data itself ?  From my understanding it's validating the "type" only. 

something like : 

```
const stringify = fastJson({
  title: 'Example Schema',
  type: 'object',
  properties: {
    nickname: {
      type: 'string'
    },
    mail: {
      type: 'string',
      customValidator : [promise1, promise2, promise3]
    }
  }
})```

`customValidator` represent an array of `promises` that will validate the data. 

Thanks

**Comment by mcollina** [comment]
This is not part of the scope of this library. It's not really to validate the data - it's for rendering it to string.
