### ISSUE TITLE
Error when using anyOf with objects using different required props

### ISSUE THREAD

**Issue by mjwwit** [fastify/fast-json-stringify#155]
The `anyOf` implementation does not properly support objects with different properties and different required properties.

Example:
```js
const result = fjs(
  {
    type: 'object',
    anyOf: [
      {
        properties: {
          baz: { type: 'number' },
        },
        required: ['baz'],
      },
      {
        properties: {
          bar: { type: 'string' },
        },
        required: ['bar'],
      },
    ],
  }
)(
  {
    baz: 42,
  }
)

// result will be '{}', expected '{"baz":42}'
```

The only way around this is by changing the schema to:

```js
  {
    type: 'object',
    properties: {
      baz: { type: 'number' },
      bar: { type: 'string' },
    },
    anyOf: [
      {
        required: ['baz'],
      },
      {
        required: ['bar'],
      },
    ],
  }
```

But this is semantically different from the first schema, and it still doesn't correcly check the required properties; stringifying `{foo: 42}` will result in `"{}"`, but should throw an error.

**Comment by mcollina** [comment]
Would you like to send a PR to fix this issue?

**Comment by mjwwit** [comment]
I could give it a go.

**Comment by mjwwit** [comment]
I've put some time into researching the issue. As it turns out, the above example has no supporting code whatsoever. Top-level `anyOf`s seem to not be supported at all? Either way, this isn't the actual issue I'm running into, just a simplified version.
In order to find the issue there, I nested the example schema inside of an object, since `anyOf`s seem to be supported in nested schemas. That led me to the actual problem; all of the nested schemas in an `anyOf` statement lead to a separate serialization function that will conditionally execute. These functions are given names, and that's where the problem lies; they're all given the same name. This means the last one gets executed for every schema in the `anyOf`, and this doesn't always match...

I'll see if I can work out a fix without breaking existing functionality.
