### ISSUE TITLE
[Feature Request]: Allow return "errors" instead of throwing

### ISSUE THREAD

**Issue by dalisoft** [fastify/fast-json-stringify#169]
Hello and thanks for this library.
For my case, this library improves Request/second by 3-7% which is good for me.
But when schema fails, i want get error by string and show to users.

Using try/catch decreases performance by ~40% for my app. Is there any way get it or available options?

PS: I'm not using `fastify`, i made own library :)

**Comment by mcollina** [comment]
Can you make an example? This library perform some crude validation, it’s not a full json schema validator anyway. I’m happy to take a PR for this that support this behavior behind flag.

**Comment by dalisoft** [comment]
Example

```js
const stringify = fastJsonStringify(schema);

stringify(object); // if fails, it throws

```

I try make PR for flag for this feature

**Comment by dalisoft** [comment]
@mcollina Sorry, i tried make PR for this, but there 101 options need to be pasted. Maybe i can't understand code-base correctly.

I currently don't have time, but try in next week, ok?

Thanks for library

**Comment by dalisoft** [comment]
@mcollina Done, #172
