### ISSUE TITLE
[Question]: How it's so fast?

### ISSUE THREAD

**Issue by dalisoft** [fastify/fast-json-stringify#170]
@mcollina 

I don't know Discussion is possible or not, how it's fast? I'm built own stringify which `Fastest` possible way and then benchmarked.
I am very shocked. `fast-json-stringify` is 2-times faster than my module. How it's possible?

You're doing things that faster than JS :)

**Comment by dalisoft** [comment]
Would be be diss in Closed issue as this isn't real issue

**Comment by dalisoft** [comment]
Here some benchmark:
```sh
dalisoft-MBP:fast-json-stringify dalisoft$ node bench.js
FJS creation x 27,932 ops/sec ±1.68% (85 runs sampled)
JSON.stringify array x 2,665 ops/sec ±1.11% (84 runs sampled)
fast-json-stringify array x 3,859 ops/sec ±0.90% (90 runs sampled)
fast-json-stringify-uglified array x 3,907 ops/sec ±0.87% (88 runs sampled)
json-strify array x 2,922 ops/sec ±1.00% (89 runs sampled)
JSON.stringify long string x 11,530 ops/sec ±0.95% (87 runs sampled)
fast-json-stringify long string x 10,373 ops/sec ±6.15% (80 runs sampled)
fast-json-stringify-uglified long string x 11,480 ops/sec ±0.95% (89 runs sampled)
json-strify string x 89,569,204 ops/sec ±2.68% (84 runs sampled)
JSON.stringify short string x 5,967,847 ops/sec ±0.87% (86 runs sampled)
fast-json-stringify short string x 14,861,540 ops/sec ±0.91% (90 runs sampled)
fast-json-stringify-uglified short string x 14,537,727 ops/sec ±0.87% (87 runs sampled)
json-strify short string x 669,388,281 ops/sec ±1.27% (89 runs sampled)
JSON.stringify obj x 1,275,629 ops/sec ±1.19% (86 runs sampled)
fast-json-stringify obj x 6,959,771 ops/sec ±0.97% (88 runs sampled)
fast-json-stringify-uglified obj x 7,057,435 ops/sec ±0.87% (89 runs sampled)
json-strify obj x 3,193,521 ops/sec ±0.98% (90 runs sampled)
```

**Comment by davidmarkclements** [comment]
related: https://github.com/davidmarkclements/v8-perf

if you're not using a schema (which is where the real speed benefits come in with this module), 
then you're actually benchmarking against [fast-safe-stringify](https://github.com/davidmarkclements/fast-safe-stringify) (which is the fallback when a schema isn't provided).

**Comment by dalisoft** [comment]
@mcollina Amazing, i also hope someday learn a lot of performance secrets like you're 👍 

I now understand how it works, it creates new function with `precompiled` (or `prepared`) function.

**Comment by dalisoft** [comment]
@davidmarkclements I think my library little faster than `fast-safe-stringify`, but i will benchmark anyway. Performance of your library should be higher as you already tried many ways to optimized code and know what makes it fast, what's not

**Comment by davidmarkclements** [comment]
@dalisoft I've looked at your code, it will be faster. But it will also enter an infinite loop if handed an object with a circular reference, and it will copy prototype properties over, whereas `JSON.stringify` will not. If these are deliberate trade-offs that's cool, but be sure to document the risks

**Comment by dalisoft** [comment]
@davidmarkclements Thanks for tip, i will do
