### ISSUE TITLE
Package adds runtime dependencies in devDependencies

### ISSUE THREAD

**Issue by amaschas** [fastify/fast-json-stringify#186]
## 🐛 Bug Report

Several runtime dependencies of this package are listed in devDependencies, which means they only get installed at build time, and are unavailable at runtime.

## To Reproduce

Install `fast-json-stringify` via `npm`, add it to any application and import it.

## Expected behavior

The app runs without errors or warnings.

Paste the results here:

```
advice_1  | WARNING in ./node_modules/fast-json-stringify/index.js
advice_1  | Module not found: Error: Can't resolve 'long' in '/usr/src/app/node_modules/fast-json-stringify'
advice_1  |  @ ./node_modules/fast-json-stringify/index.js
advice_1  |  @ ./node_modules/koa2-winston/stringify_schema.js
advice_1  |  @ ./node_modules/koa2-winston/index.js
advice_1  |  @ ./src/server/server.ts
advice_1  |  @ ./src/server/index.ts
advice_1  |
advice_1  | WARNING in ./node_modules/fast-json-stringify/index.js
advice_1  | Module not found: Error: Can't resolve 'uglify-es' in '/usr/src/app/node_modules/fast-json-stringify'
advice_1  |  @ ./node_modules/fast-json-stringify/index.js
advice_1  |  @ ./node_modules/koa2-winston/stringify_schema.js
advice_1  |  @ ./node_modules/koa2-winston/index.js
advice_1  |  @ ./src/server/server.ts
advice_1  |  @ ./src/server/index.ts
advice_1  |
advice_1  | WARNING in ./node_modules/fast-json-stringify/index.js
advice_1  | Module not found: Error: Can't resolve 'uglify-es/package.json' in '/usr/src/app/node_modules/fast-json-stringify'
advice_1  |  @ ./node_modules/fast-json-stringify/index.js
advice_1  |  @ ./node_modules/koa2-winston/stringify_schema.js
advice_1  |  @ ./node_modules/koa2-winston/index.js
advice_1  |  @ ./src/server/server.ts
advice_1  |  @ ./src/server/index.ts
```

and then crashes with

```
advice_1  | (node:178) UnhandledPromiseRejectionWarning: ReferenceError: $asNumber is not defined
advice_1  |     at eval (eval at e.exports (/usr/src/app/dist/js/webpack:/node_modules/fast-json-stringify/index.js:134:20), <anonymous>:15:24)
advice_1  |     at apply (/usr/src/app/dist/js/webpack:/node_modules/fast-json-stringify/index.js:134:50)
advice_1  |     at fastJson (/usr/src/app/dist/js/webpack:/node_modules/koa2-winston/stringify_schema.js:182:21)
advice_1  |     at Object.generateFormat [as logger] (/usr/src/app/dist/js/webpack:/node_modules/koa2-winston/index.js:88:27)
advice_1  |     at Object.logger [as initServer] (/usr/src/app/dist/js/webpack:/src/server/server.ts:129:57)
advice_1  |     at initServer (/usr/src/app/dist/js/webpack:/src/server/index.ts:28:23)
advice_1  |     at Object.init (/usr/src/app/dist/js/webpack:/src/server/index.ts:60:1)
advice_1  |     at call (/usr/src/app/dist/js/webpack:/webpack/bootstrap:19:22)
advice_1  |     at __webpack_require__ (/usr/src/app/dist/js/webpack:/webpack/bootstrap:83:10)
advice_1  |     at Object.<anonymous> (/usr/src/app/dist/js/adviceServer.js:1:913)
advice_1  | (node:178) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
advice_1  | (node:178) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Which indicates that either long or uglify-es is required for something at runtime.

## Your Environment

- *node version*: 6.9.0
- *fastify version*: 1.15.3
- *os*: Mac
- I'm using `fast-json-stringify` as a dependency of `koa2-winston`.

**Comment by mcollina** [comment]
You are transpiling this module, and you should put some extra care while doing it. It’s not meant to be transpiled.

**Comment by amaschas** [comment]
I don't think transpiling is the culprit here, and in any case this package is getting used as a downstream dependency of other packages in cases where it will, 100%, be transpiled. The issue is that there's a package that's required at runtime that doesn't appear to be installed at runtime. If I manually install the `long` and `uglify-es` packages the runtime error goes away.

**Comment by jsumners** [comment]
Duplicate #67 #95 #149 

Relevant code:

https://github.com/fastify/fast-json-stringify/blob/03082ebca421bf4aaaae694b248149cfdac10b7c/index.js#L10-L16

https://github.com/fastify/fast-json-stringify/blob/03082ebca421bf4aaaae694b248149cfdac10b7c/index.js#L1016-L1027

**Comment by gajus** [comment]
@mcollina how is no one addressing this issue?

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mcollina** [comment]
> @mcollina how is no one addressing this issue?

I highly recommend to read the related issues. Essentially it's like this on purpose. Considering yarn and pnpm we might want to change this in the future and possibly drop long.js support.

**Comment by gajus** [comment]
> Would you like to send a Pull Request to address this issue? Remember to add unit tests.

How would one write a test case for checking if long is a devDependency or a direct dependency?

**Comment by gajus** [comment]
> I highly recommend to read the related issues. Essentially it's like this on purpose. Considering yarn and pnpm we might want to change this in the future and possibly drop long.js support.

@mcollina I read the related issues. Where is it documented that `long` is an optional dependency and that it should be installed separately?

This could be just a documentation issue, but it was not clear when starting to use the module.

**Comment by mcollina** [comment]
likely just a docs issue :)

**Comment by gajus** [comment]
@mcollina We were discussing this in our team, and while we can ignore the warning, since this is optional dependency, it would be nice if you gave an option to control whether `long` is used.

So the code would look something like:

```diff
-let isLong
-try {
-  isLong = require('long').isLong
-} catch (e) {
-  isLong = null
-}

function build (schema, options) {
+  let isLong = null
+  if (option.useLong) {
+    isLong = require('long').isLong;
+  }

```

and since user opts-in explicitly to use `long`, the code rightfully should fail here if dependency is not available when requested.

**Comment by mcollina** [comment]
that'd be great as a PR!

**Comment by gajus** [comment]
https://github.com/fastify/fast-json-stringify/pull/284
