### ISSUE TITLE
String integer converts to null if type is ['integer', 'null']

### ISSUE THREAD

**Issue by ZiiMakc** [fastify/fast-json-stringify#191]
If ajv schema is set to ['integer', 'null']:

```

const settings = {
  removeAdditional: true,
  useDefaults: true,
  coerceTypes: true, 
  allErrors: true
}

var schema =  {
    $id: 'posIntNull',
    type: ['integer', 'null'],
    minimum: 1
},
```
And you have bigint integer with type of string '2312312' loaded from database, then string integer converts into null on res.send, instead of integer 2312312.

```
fastify.route({
    method: 'POST',
    url: '/api',
    schema: {
      response: {
        200: {
          type: 'object',
          properties: {
            id: 'posIntNull#',
          }
        }
      }
    },
    handler: async (req, res) => {
      return res.send({ id: '12312321313'})
    }
  })
```

If schema is set to 'integer' without 'null', than it's works fine.

Is this is bug or it's normal behavior and i just need to use string for big integers?

**Comment by mcollina** [comment]
This looks like a bug, would you like to send a PR?

**Comment by ReTWi** [comment]
@mcollina was trying to understand source code, but didn't succeed :( 
So i can't take PR.

But on the bright side, i found that you can use "nullable: true" and everything will work fine:
```
var schema =  {
    $id: 'posIntNull',
    type: 'integer',
    nullable: true
}
```
