### ISSUE TITLE
Support multiple types in one schema

### ISSUE THREAD

**Issue by KostyaZgara** [fastify/fast-json-stringify#193]
## 🚀 Feature Proposal

Hi,  I'm using `fastify` and I know that `fastify` use `fast-json-stringify` underhood in serialization. Will be better if `fast-json-stringify` will support multiple types. For example

```js
{
  type: ['object', 'string'],
  properties: {
    foo: {
      type: 'string'
    }
}
```

So property `foo` can be string or `object`

## Motivation

I'm using `fastify` with MongoDB where all ids are `ObjectId` and `fast-json-stringify` can't properly determine that `ObjectId` can be serialized to a simple string. Also, a field that contains `ObjectId` can be expanded and be a plain object with nested properties. So one field can be either `ObjectId` that should be properly serialized to `string` or plain object with nested properties that should be serialized as `object`.
Also, I have tried to use `anyOf` keyword but I did get the same result.

## Example
I can provide a code example with current behavior:

```js
const { ObjectId } = require('bson');
const fastJson = require('fast-json-stringify');

const stringify = fastJson({
  type: 'object',
  properties: {
    user: {
      type: ['object', 'string'],
      properties: {
        id: {
          type: ['object', 'string'],
        },
        name: {
          type: 'string',
        },
      },
    },
  },
});

const stringifyAnyOf = fastJson({
  type: 'object',
  properties: {
    user: {
      anyOf: [
        { type: 'string' },
        {
          type: 'object',
          properties: {
            id: {
              type: ['object', 'string'],
            },
            name: {
              type: 'string',
            },
          },
        }
      ],
    },
  },
});

const id = new ObjectId();

const dataWithObjectId = {
  user: id,
}

const dataWithExpandedUser = {
  user: {
    id,
    name: 'John',
  },
};

console.log(`Current id: ${id}`)
// serialize with type: ['object', 'string']
console.log(stringify(dataWithObjectId));
console.log(stringify(dataWithExpandedUser));
// serialize with anyOf
console.log(stringifyAnyOf(dataWithObjectId));
console.log(stringifyAnyOf(dataWithExpandedUser));
```

### Likn to repl
https://repl.it/@KostyaZgara/fast-json-stringify 

Current behavior:
```json
Current id: 5dc2a3ba50a3a8d8f1b73f30
{"user":{}}
{"user":{"id":{},"name":"John"}}
{"user":{}}
{"user":{"id":{},"name":"John"}}
```

Expected behavior:
```json
Current id: 5dc2a3ba50a3a8d8f1b73f30
{"user": "5dc2a3ba50a3a8d8f1b73f30" }
{"user":{"id":"5dc2a3ba50a3a8d8f1b73f30","name":"John"}}
{"user":"5dc2a3ba50a3a8d8f1b73f30"}
{"user":{"id":"5dc2a3ba50a3a8d8f1b73f30","name":"John"}}
```

Can you add new feature or say another approach that could help me?
Thanks in advance!

**Comment by mcollina** [comment]
This would be really good to add, as it's valid json schema syntax https://json-schema.org/understanding-json-schema/reference/type.html! Would you like to send a PR to add it?

**Comment by KostyaZgara** [comment]
I'm not sure that I will have enough time, but I will try as soon as possible. Thanks for the answer!

**Comment by jsumners** [comment]
Shouldn't your opening example be?:

```js
{
  type: 'object',
  properties: {
    foo: {
      type: ['object', 'string']
    }
}
```

**Comment by mum-never-proud** [comment]
I can raise a pr is this not already done

**Comment by mcollina** [comment]
I think it’s not, PRs are welcome.

**Comment by DanilaFadeev** [comment]
@mum-never-proud @mcollina Are any updates on this feature?

**Comment by mcollina** [comment]
This needs somebody to work on it.

**Comment by Eomm** [comment]
> fast-json-stringify can't properly determine that ObjectId can be serialized to a simple string

How could we know if an object could be a string or not without checking the `toString` function?

Because if we look at the `toString` function, the output would be:

```
{ "user": "5dc2a3ba50a3a8d8f1b73f30" }
{ "user": "[object Object]" }
```

Running `obj.toString() !=== "[object Object]"` doesn't seems a good answer for me since we could run the `toString` more than one and when not needed.

I think to solve this use case, a new `options` should be set by the user.

Does someone have a better idea?

**Comment by mcollina** [comment]
typeof has the proper return value.

**Comment by Eomm** [comment]
> typeof has the proper return value.

I don't understand.

In this case `typeof obj.user.toString === 'function'` would return `true` if the user is a string and if it is a JSON too

**Comment by jsumners** [comment]
```js
typeof [] === 'object' // 'true'
```

**Comment by Eomm** [comment]
We should try because the dates follow the same flow

**Comment by Eomm** [comment]
I tweak a bit and I'm opening a PR to explain better the case tho.


```
const value = { toString(){ return 'hello' } }
```

the user want to serialize `{ foo: value }` but `value` is an **object** with a **`toString`** function.
_This is fine if the user defines `type: string` since it is already coerced calling the `toString` function._

Now the user defines the type `type: [string, object]`.

How `fast-json-stringify` could choose when serializing an object calling the `toString` **or** exploring the object itself?

In this case, these booleans are always `true`:

- typeof value is `object`
- typeof value.toString is `function`

**Comment by mcollina** [comment]
For `type: ['string']`, we'd need to check `Object.prototype.hasOwnProperty.call(obj, 'toString')`.

**Comment by Eomm** [comment]
Closing due merge

**Comment by gfortaine** [comment]
@KostyaZgara => `simultaneously` should do the trick 👍  :

```javascript
const { ObjectId } = require("bson");
const fastJson = require("fast-json-stringify");

const build = fastJson({
  type: "object",
  properties: {
    user: {
      simultaneously: {
        type: ["string", "object"],
        properties: {
          id: {
            type: "string",
          },
          name: {
            type: "string",
          },
        },
      },
    },
  },
});

const id = new ObjectId();
const dataWithObjectId = {
  user: id,
};

const dataWithExpandedUser = {
  user: {
    id,
    name: "John",
  },
};

console.log(`Current id: ${id}`);
// serialize with anyOf
console.log(build(dataWithObjectId));
console.log(build(dataWithExpandedUser));
```

thx @Eomm 🚀

**Comment by gfortaine** [comment]
@KostyaZgara 

```javascript
const { ObjectId } = require('bson');
const fastJson = require('fast-json-stringify');

const stringify = fastJson({
  type: 'object',
  properties: {
    user: {
      simultaneously: {
        type: ['object', 'string']
      }
    }
  },
});

const id = new ObjectId();

const dataWithObjectId = {
  user: id,
}

const dataWithExpandedUser = {
  user: {
    id,
    name: 'John',
  },
};

console.log(`Current id: ${id}`)
// serialize with type: ['object', 'string']
console.log(stringify(dataWithObjectId));
console.log(stringify(dataWithExpandedUser));

**Comment by gfortaine** [comment]
@KostyaZgara Here is another implementation based on [AJV JTD Serializer ](https://ajv.js.org/guide/getting-started.html#parsing-and-serializing-json) that should ensure better soundness regarding the validation of the schema cc @epoberezkin

```javascript
const Ajv = require("ajv/dist/jtd");
const instanceofDef = require("ajv-keywords/dist/definitions/instanceof");
const { ObjectId } = require("bson");

const ajv = new Ajv(); // options can be passed, e.g. {allErrors: true}

// https://github.com/ajv-validator/ajv-keywords#instanceof
instanceofDef.CONSTRUCTORS.ObjectId = ObjectId;

// https://github.com/ajv-validator/ajv/issues/147#issuecomment-199371370
ajv.addKeyword({
  keyword: "instanceof",
  schemaType: "string",
  compile: (schema) => {
    const Class = instanceofDef.CONSTRUCTORS[schema];

    return (data) => data instanceof Class;
  },
});

const schema = {
  properties: {
    user: {
      metadata: {
        union: [
          {
            metadata: {
              instanceof: "ObjectId",
            },
          },
          {
            properties: {
              id: {
                metadata: {
                  instanceof: "ObjectId",
                },
              },
              name: { type: "string" },
            },
          },
        ],
      },
    },
  },
};

const validate = ajv.compile(schema);
const serialize = ajv.compileSerializer(schema);

const id = new ObjectId();

const dataWithObjectId = {
  user: id,
};

const dataWithExpandedUser = {
  user: {
    id,
    name: "John",
  },
};

console.log(`Current id: ${id}`);

function validateAndSerialize(data) {
  const valid = validate(data);

  if (valid) {
    console.log(serialize(data));
  } else {
    console.log("invalid", validate.errors);
  }
}

for (const data of [dataWithObjectId, dataWithExpandedUser]) {
  validateAndSerialize(data);
}
