### ISSUE TITLE
Add support for Moment.JS

### ISSUE THREAD

**Issue by ilaif** [fastify/fast-json-stringify#194]
## 🚀 Feature Proposal

Given an object to stringify, if it contains properties of type Moment.JS, it should handle it correctly, or support extensibility for the user to do so.

## Motivation

Moment.JS (among other datetime libraries) are very common. As a Fastify user, I'm using Ajv to transform date-time input into Moment.JS, which I move around the code, and when I return a response that contains Moment.JS properties, I would like for the serialization library to format it automatically, just like it handles vanilla Date objects.

## Example

The following example should stringify the `time` property in an ISO format.

```js
const moment = require('moment')

const stringify = fastJson({
  title: 'Time Schema',
  type: 'object',
  properties: {
    time: {
      type: 'string',
      format: 'date-time',
    },
  }
})

const payload = {
  time: moment(),
}

console.log(stringify(payload))
```
* I'm not sure that the schema should say the time is of type 'string' since we pass an object to it (moment.js object).

I understand that inserting non-vanilla logic into the library is probably not the right way, but providing a way to extend the library with external logic (like in Ajv) sounds like a good balance.

**Comment by jsumners** [comment]
1. Doesn't the `moment` object already stringify correctly?
2. Why not? `const payload = { time: moment().toDate() }`

**Comment by ilaif** [comment]
1. The library reads it as not object and outputs "{}".
2. It means I have to maintain this in the code in every reply. I can just do moment().toISOString() if I go that way, but I want it handled automatically.

**Comment by mcollina** [comment]
I think supporting it would be a good feature to add, essentially we would like to call .toIsoString() if date-time format is specified. Would you like to send a PR?

**Comment by ilaif** [comment]
Glad to hear! Will do.

**Comment by ilaif** [comment]
Opened a PR: https://github.com/fastify/fast-json-stringify/pull/195
