### ISSUE TITLE
comparison with fast-safe-stringify

### ISSUE THREAD

**Issue by mesqueeb** [fastify/fast-json-stringify#199]
## 💬 Questions and Help

I'm looking for a JSON stringify function and am doubting between these two packages:
- [fast-json-stringify](https://github.com/fastify/fast-json-stringify)
- [fast-safe-stringify](https://github.com/davidmarkclements/fast-safe-stringify)

Is it possible to add some comparison and/or benchmarks between these two?

**Comment by mcollina** [comment]
What’s your idea? The README should express enough info to draw your conclusions.

**Comment by Eomm** [comment]
I think the target of these modules is different:

+ fast-json-stringify needs a JSON schema as input: you know what you are serializing (with the [flexibility to choose](https://github.com/fastify/fast-json-stringify#additional-properties))
+ fast-safe-stringify serialize JSON without knowing it plus more checks like circular references

For this reason, it would be unfair comparing them

**Comment by mesqueeb** [comment]
Thanks this is a good comparison ! 😊
