### ISSUE TITLE
Support `anyOf` at root when `type` is absent

### ISSUE THREAD

**Issue by chengluyu** [fastify/fast-json-stringify#200]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

## 🚀 Feature Proposal

Support `anyOf` at root when `type` is absent.

## Motivation

Following schema is valid.

```js
const schema = {
  '$schema': 'http://json-schema.org/draft-07/schema#',
  anyOf: [
    { type: 'object', properties: { include: { type: 'string' } } },
    { type: 'object', properties: { exclude: { type: 'string' } } }
  ]
};
const validate = ajv.compile(schema);
validate({ include: 'me' }); // true
```

But fast-json-stringify doesn't accepts it.

```js
// This will throw "Error: undefined unsupported"
const stringify = fastJson(schema);
```

It seems that fast-json-stringify requires `type` on the root of the input schema.
https://github.com/fastify/fast-json-stringify/blob/24d58f7924aeb7c5bb4b8636c251a782b323e05e/index.js#L114

## Example

Yeah, I know support `anyOf` may slow down the performance. But it's quite common that the object you want to serialize is of two different disjoint types.

Suppose the schema of two types are `schema1` and `schema2`. Of course, we can write a schema that manually combine properties from them. But it's more convenient if we can just use `{ anyOf: [schema1, schema2] }`, right?

**Comment by jsumners** [comment]
It may be valid, but I argue that it is ambiguous.

> But it's quite common that the object you want to serialize is of two different disjoint types.

It may be common in your environment, but I haven't encountered any environments where such ambiguity is common or even accepted.

**Comment by mcollina** [comment]
I fully agree to what James said about the usefulness of supporting anyOf. I
don’t think it’d be recommendable to use it with this module (or at all). That being said, I’m _always_ in favor of improving spec compatibility. anyOf support can be improved significantly (especially in recursive anyOf), if you’d like to help.

**Comment by chengluyu** [comment]
I'm beginning to agree with you. My use cases are some fastify routes in which the response is one of two (or more) types which have disjoint properties. In the perspective of clients, the response is ambiguous because the client need test multiple properties to know the type. My final solution is add an additional property named `kind` so I can make use of if-then-else. Thanks you guys.
