### ISSUE TITLE
The library code is crashed, and it doesn't even give a rough idea of what's wrong or how to fix it.

### ISSUE THREAD

**Issue by petrovi4** [fastify/fast-json-stringify#201]
For me the project is in a terrible condition as far as debugging is concerned. 
Edited the schema. Running it. 
I'm getting error 

```javascript
.../node_modules/fast-json-stringify/index.js:489
    if (schema.$ref) {
               ^
TypeError: Cannot read property '$ref' of undefined
```

What does it mean, how to debug it, how to fix it - I don't understand. 
I have to debug the code of the library itself or comment my scheme in parts to finally find the problem area. 
This is very embarrassing. 

Maybe I'm doing something wrong. 
How do other developers deal with it?

**Comment by mcollina** [comment]
Well, we can understand the code that it's in here. I agree that's not the best to maintain.

The starting point of opening a bug report and trying a fix is to write a small example that reproduce the problem. Otherwise it would be really hard for us to help.

**Comment by StarpTech** [comment]
This lib is a niche product. If you don't need raw performance use the native methods. If you need it, be patient and open to help. Your issue description is useless.

**Comment by petrovi4** [comment]
> The starting point of opening a bug report and trying a fix is to write a small example that reproduce the problem. Otherwise it would be really hard for us to help.

> Your issue description is useless

The fact of the matter is that there is no information about the error. 
Take for example the last error I was struggling with. 
It concerns this code:

```javascript
function refFinder (ref, schema, externalSchema) {
  // Split file from walk
  ref = ref.split('#')

  // If external file
  if (ref[0]) {
    schema = externalSchema[ref[0]]

    if (schema.$ref) {
```
In the last line of code, the application crashes because schema is null, i.e. not found. 
What prevented you from checking schema, and if it is null throw an error, specifying in it for which ref this error occurred? Nothing interfered. 
But the developer would immediately see in what part of his big scheme the error is. 
It could have just been a typo (as it was in my case). 

Instead, you have to check object by object, line by line, in which part of the big scheme the error is. 

It's not that it's niche, but that this particular piece of code was written without thinking about convenient debugging. 

The project is excellent, and it fits perfectly for many tasks, but it has a number of drawbacks, one of which is inconvenient debugging and incomprehensible crashes.

**Comment by mcollina** [comment]
Can you please clarify exactly what bug are you reporting? Can you make an example of what is causing the crash?

**Comment by petrovi4** [comment]
I didn't create this issue as an error. It was a question.
And the question was, perhaps someone else encountered any obscure errors when working with fast-json-stringify and how they were identified. 

Here is an example (attention to SomeDTO_TYPO):

```javascript
definitions: {

	SomeDTO: {
		type: 'object',
		properties: {
			id: { type: 'integer' },
		},
	},

	SomeDTOArray: {
		type: 'array',
		items: { $ref: 'someDTO#/definitions/SomeDTO_TYPO' },
	},
};
```
When trying to interpret this code as a part of schema, fast-json-stringify crashes with an error
```
.../node_modules/fast-json-stringify/index.js:489
    if (schema.$ref) {
               ^
TypeError: Cannot read property '$ref' of undefined
```

**Comment by jsumners** [comment]
Please just add a full example that will reproduce the error. One were we can copy and paste it into an `index.js` and run `node index.js` to see the error happen.

**Comment by delvedor** [comment]
I agree that the debugging experience of this library can be improved, but **your tone** here is the real issue.
We will **not tolerate** this kind of behavior. 
I urge you to read our [code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md), then open a new issue and follow one of the issues templates.

**Comment by petrovi4** [comment]
Here's an example of what I'm talking about

```javascript
let fastJson = require('fast-json-stringify');

fastJson({
  type: 'object',
  properties: {
    data: {
      $ref: 'ext#/definitions/SomeDTO_TYPO',
    },
  },
}, {
  schema: {
    ext: {
      definitions: {
        SomeDTO: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
          },
        },
      },
    },
  },
});
```

The error looks like this:
```
...node_modules/fast-json-stringify/index.js:517
  return result.$ref ? refFinder(result.$ref, schema, externalSchema) : result
                ^
TypeError: Cannot read property '$ref' of undefined
...
```
