### ISSUE TITLE
Move to GitHub actions

### ISSUE THREAD

**Issue by delvedor** [fastify/fast-json-stringify#203]
We are still using Travis and Azure Pipelines.
I think we can drop them both and move to GitHub actions :)

**Comment by mcollina** [comment]
Definitely!
Il 17 gen 2020, 23:02 +0100, Tomas Della Vedova <notifications@github.com>, ha scritto:

**Comment by delvedor** [comment]
Closed in https://github.com/fastify/fast-json-stringify/pull/211.
