### ISSUE TITLE
Mandatory items for type array

### ISSUE THREAD

**Issue by Eomm** [fastify/fast-json-stringify#204]
# 🐛 Bug Report

For types `array` the `items` key is not mandatory by the standard, but it is needed by fast-json-stringify.
We should set a default instead

## To Reproduce

```js
var fastJsonStringify = require("fast-json-stringify")
const str = fastJsonStringify({
  "type": "object",
  "properties": {
    "foo": {
      "type": "array"
       // , items: { type: 'string' } // uncomment to let it works
    }
  }
})
```

## Expected behavior

The type of the item's array should be `any`

## Your Environment

- *node version*: 10
- *jast-json-stringify*: 1.16.1
- *os*: Windows 10

**Comment by mcollina** [comment]
Definitely!

**Comment by agarwalkartik** [comment]
The **Expected Behaviour** in the issue calls for the item type to be `any`.

AFAIK, there is not `any` type in this module, would this issue require to add a new `any` type which just accepts any valid json ?
