### ISSUE TITLE
Runkit Example

### ISSUE THREAD

**Issue by Eomm** [fastify/fast-json-stringify#205]
## 🚀 Feature Proposal

Following [these](http://blog.runkit.com/2015/10/28/npm-plus-runkit/) docs it would be possible to add a default example in [runkit](https://npm.runkit.com/fast-json-stringify) (like [ajv](https://npm.runkit.com/ajv) does).

## Motivation

It is very useful for users to play with the module and to create a snippet to share (like in bug report and so on)

## Example

Maybe we could just:
- [ ] create an example file from the readme
- [ ] write a test in order to don't let the example old

**Comment by mcollina** [comment]
Nice!

**Comment by agarwalkartik** [comment]
I guess it is as simple as copying the example from readme into a new runkit project, which I already did here https://runkit.com/agarwalkartik/fast-json-stringify-example.

But shouldn't this be done with `fast-json-stringify`'s account ?

**Comment by Eomm** [comment]
> But shouldn't this be done with fast-json-stringify's account ?

Reading the docs we need a file in this repo

**Comment by agarwalkartik** [comment]
Oh got it!!

There is already a file "example.js", can we use it?? Then we just need to add 
```
"runkitExampleFilename" : "example.js"
```
in the package.json file.

Also any idea on how do we make sure that example is not old? And, is this a good idea to make sure that example is always correct?

**Comment by mcollina** [comment]
We currently do not test it, but it’s very unlikely to change. Would you like to send a PR?

**Comment by agarwalkartik** [comment]
Yes would love to,  but my question still remains the same.

- How do we make sure that example is not old?
- And just to be clear, you are suggesting we skip the test case for example.
