### ISSUE TITLE
'Infinite' numbers are returned in JSON output

### ISSUE THREAD

**Issue by maximilian-krauss** [fastify/fast-json-stringify#221]
#  🐛 Bug Report

If the serialized data contains a number field with an `Infinite` value it's being serialized as `{"value": Infinite}` which produces an invalid JSON.

Is this an expected behavior?

## To Reproduce

```js
const fast = require("fast-json-stringify")
const stfy  = fast({
  type: 'object',
  required: ['a'],
  properties: {
    a: { type: 'number' }
  }
})
const obj = { a: Infinity }
console.log(stfy(obj)) // => "{\"a\":-Infinity}"
console.log(JSON.stringify(obj)) // => "{\"a\":null}"
```
Runkit: https://runkit.com/maximilian-krauss/5eb27a8a3651fb001a5b6521

## Expected behavior

Output should be `null`.

## Your Environment

- *node version*: 12
- *fastify version*: >=2.0.0
- *os*: Mac

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by maximilian-krauss** [comment]
Yes, sure 🙂
