### ISSUE TITLE
allOf does not support $ref

### ISSUE THREAD

**Issue by joelmukuthu** [fastify/fast-json-stringify#223]
## 🐛 Bug Report

With `allOf`, a schema that is referenced via `$ref` gets stripped out of the stringified output. 

## To Reproduce

```js
const fastJson = require('fast-json-stringify');
const stringify = fastJson({
  type: 'object',
  definitions: {
    names: {
      type: 'object',
      properties: {
        firstName: { type: 'string' },
        lastName: { type: 'string' },
      },
    },
  },
  properties: {
    user: {
      type: 'object',
      allOf: [{ $ref: '#/definitions/names' }],
    },
  },
});

console.log(stringify({ user: { firstName: 'john', lastName: 'doe' } })); // {"user":{}}
```

## Expected behavior

That `firstName` and `lastName` would be included in the output. Compare with the following where `$ref` is not used:

```js
const fastJson = require('fast-json-stringify');
const stringify = fastJson({
  type: 'object',
  definitions: {
    names: {
      type: 'object',
      properties: {
        firstName: { type: 'string' },
        lastName: { type: 'string' },
      },
    },
  },
  properties: {
    user: {
      type: 'object',
      allOf: [
        {
          type: 'object',
          properties: {
            firstName: { type: 'string' },
            lastName: { type: 'string' },
          },
        },
      ],
    },
  },
});

console.log(stringify({ user: { firstName: 'john', lastName: 'doe' } })); 
// {"user":{"firstName":"john","lastName":"doe"}}
```

## Your Environment

- *node version*: 12.6.1
- *fast-json-stringify*: 2.0.0
- *os*: Linux

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by joelmukuthu** [comment]
Sure thing. Would you mind jump starting me in the right direction, the
codebase looked quite cryptic at first glance earlier today.

**Comment by mcollina** [comment]
We should do something similar to https://github.com/fastify/fast-json-stringify/blob/c4fbf833cacf4a97a18f2d3b2217d9a4188dc030/index.js#L632 in https://github.com/fastify/fast-json-stringify/blob/c4fbf833cacf4a97a18f2d3b2217d9a4188dc030/index.js#L736.

I think we should pass through the definitions.

**Comment by ahgentil** [comment]
I'm experiencing a similar issue that is probably related:

In my schema's "response":

```
    200: {
      type: 'array',
      items: {
        anyOf: [
          { $ref: 'someref1' },
          { $ref: 'someref2' }
        ]
      }
    }
```
This does not work.

**Comment by joelmukuthu** [comment]
I've submitted [a PR](https://github.com/fastify/fast-json-stringify/pull/224) for this.

@ahgentil, I haven't tested it with actual code but it looks like `$ref` in `anyOf` does work. This test is already on master and passing: https://github.com/fastify/fast-json-stringify/blob/c4fbf833cacf4a97a18f2d3b2217d9a4188dc030/test/anyof.test.js#L252-L295

Consider creating a new issue with some code that can fully reproduce your case.
