### ISSUE TITLE
Required property not set in properties

### ISSUE THREAD

**Issue by davidebianchi** [fastify/fast-json-stringify#225]
## 🐛 Bug Report

A required property not set in properties is not checked also if set as required. This whether it is set with additionalProperties to true and to false.

## To Reproduce

```js
test('object with required field not in properties schema', (t) => {
  const schema = {
    title: 'object with required field',
    type: 'object',
    properties: {
      num: {
        type: 'integer'
      }
    },
    additionalProperties: true,
    required: ['str']
  }
  const stringify = build(schema)

  try {
    stringify({})
    t.fail()
  } catch (e) {
    t.is(e.message, 'str is required!')
    t.pass()
  }
}
```

## Expected behavior

I suppose this test should pass (ref of the required property here https://tools.ietf.org/html/draft-zyp-json-schema-03#section-5.7).

Otherwise, since it is an edge case usually due to a badly generated schema, this behavior could also be documented.

## Your Environment

- *node version*: 12
- *os*: Mac

**Comment by mcollina** [comment]
Looks like you found yourself a bug! I didn’t even thought that was valid 🤦‍♂️😅.

Would you like to send a Pull Request to address this issue? Remember to add unit tests.
