### ISSUE TITLE
Fields with @ symbols that require a function to be generated are not supported

### ISSUE THREAD

**Issue by JaceHensley** [fastify/fast-json-stringify#227]
## 🐛 Bug Report

When a field name contain the `@` symbol __AND__ the type requires a function to be generated (`array` and `object`) the function's name is invalid and results in `SyntaxError: Invalid or unexpected token`.

## To Reproduce

I use the following it works great!

```js
S.object()
  .prop('@id', S.string())
  .valueOf()
```

But if that becomes an array or object it fails. It tries to create a function called `$main@id` which isn't valid

```js
S.object()
  .prop('@id', S.object())
  .valueOf()
```

## Expected behavior

I would expect it to support field names with `@` in their name. I'm not quite sure of the fix because if we just strip the '@' symbol from the function name then there could be duplicated function names if there was something like "@type" and "type" on an object. Could do a regex and replace it with "AT_SYMBOL" or something tho.

## Your Environment

- *node version*: 10
- *fastify version*: >=2.0.0
- *fast-json-stringify version*: 1.20.1
- *os*: Mac

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by JaceHensley** [comment]
Yes I can! What do you think the fix should be? also would it be fine if I just added it to 1.x branch (since stable fastify is still on that)?

**Comment by mcollina** [comment]
I'll forward port it.

**Comment by mcollina** [comment]
Released on both lines
