### ISSUE TITLE
Remove bad pattern from test suite

### ISSUE THREAD

**Issue by mcollina** [fastify/fast-json-stringify#229]
## 🐛 Bug Report

Our test suite is full of:

```js
  try {
    const value = stringify({
      id: 1
    })
    t.is(value, '{"id":1}')
  } catch (e) {
    t.fail()
  })
```

This is totally unnecessary and it prevents our error to bail up. It should be replaced with:

```js
    const value = stringify({
      id: 1
    })
    t.is(value, '{"id":1}')
```

**Comment by artemruts** [comment]
I'll take this one if no one minds, will propably write a codemod because there's a ton of `try-catch` in tests.

**Comment by mcollina** [comment]
Go for it!
