### ISSUE TITLE
Improve string serialization?

### ISSUE THREAD

**Issue by delvedor** [fastify/fast-json-stringify#23]
Hello @addaleax!
Me and @mcollina are working on this project, Fastify a web framework focused on performances and other very nice stuff :)
Part of the project is this module, that as you can easily image is a *schema based json serializator*.

I saw your talk at NodeConfBarcellona where you talked about character encoding.
We had some little trouble with that and our solution was [this one](https://github.com/fastify/fast-json-stringify/blob/master/index.js#L78-L117).
I was wondering if you'd like to check out the function, and help us to improve it :)

Thank you and have a nice day! :)

**Comment by addaleax** [comment]
Hi! The code looks fine to me … is there anything specific you were having trouble with?

(One small thing I just noticed: You could drop the `+ str[i]` bit in L107 and then set `last = i` instead of `last = i  +1`, right?)

**Comment by delvedor** [comment]
Maybe I'm not getting your suggestion, the idea with that for cycle is that if we find a special character, such as a `\n`, we escape it by adding a `\`. But since javascript sees `\n` as a single character we add it with `str[i]`, so the result will be `\\n`.

If I remember correctly, in your talk you said to avoid the use of `charCodeAt`. So I was asking to myself if there is a better solution. Essentially what I want is to avoid the use of `JSON.stringify` and find a way to escape every character in our code :)

**Comment by addaleax** [comment]
> Maybe I'm not getting your suggestion, the idea with that for cycle is that if we find a special character, such as a `\n`, we escape it by adding a `\`. But since javascript sees `\n` as a single character we add it with `str[i]`, so the result will be `\\n`.

So, maybe *I* am misunderstanding something, but the code doesn’t quite seem to work that way – `'\\' + '\n' === '\\\n'`, not `'\\' + '\n' === '\\n'`? If you want to escape characters like `\n`, you’ll need to know how to look up that `\n` decomposes as `\` + `n` in some way.

Currently, you only check for `"` and `\\`, right? (`point === 34 || point === 92`) For those the situation is simpler than for the other JS escape codes, because you can escape those characters by simply adding a `\` in front of them. I also think you do not need to care about characters like `\n`, you can just serialize them as they are according to http://json.org/.

> If I remember correctly, in your talk you said to avoid the use of `charCodeAt`.

That’s actually nice feedback, because maybe I wasn’t so clear – the problem with `charCodeAt()` is that it doesn’t handle characters outside of the BMP properly. If you want to check for specific characters that have code points < 65536, you will be fine using `charCodeAt()`.

**Comment by delvedor** [comment]
> So, maybe I am misunderstanding something, but the code doesn’t quite seem to work that way – '\\' + '\n' === '\\\n', not '\\' + '\n' === '\\n'? If you want to escape characters like \n, you’ll need to know how to look up that \n decomposes as \ + n in some way.

Not exactly, I write `\\` because I must escape the single `\` as well, but the result if you checkout the resulting string will be `\\n` (It got me some headache :P).

> Currently, you only check for " and \\, right? (point === 34 || point === 92) For those the situation is simpler than for the other JS escape codes, because you can escape those characters by simply adding a \ in front of them. I also think you do not need to care about characters like \n, you can just serialize them as they are according to http://json.org/.

Yes, we are using that two codes because are the most common used, so we have this "fast case".
The problem arrives when you must escape characters like `\u0008`.
Some of the discussion has been done [here](https://github.com/pinojs/pino/pull/113).

> That’s actually nice feedback, because maybe I wasn’t so clear – the problem with charCodeAt() is that it doesn’t handle characters outside of the BMP properly. If you want to check for specific characters that have code points < 65536, you will be fine using charCodeAt().

Got it, thanks! :)

**Comment by addaleax** [comment]
Ah, right, I forgot the bailout for `point < 32`. Nevermind my `\n` comments then. ;)

I still think it makes sense to do
```diff
diff --git a/index.js b/index.js
index 65d627a6214e..6642035bbc33 100644
--- a/index.js
+++ b/index.js
@@ -104,8 +104,8 @@ function $asStringSmall (str) {
   for (var i = 0; i < l && point >= 32; i++) {
     point = str.charCodeAt(i)
     if (point === 34 || point === 92) {
-      result += str.slice(last, i) + '\\' + str[i]
-      last = i + 1
+      result += str.slice(last, i) + '\\'
+      last = i
     }
   }
   if (last === 0) {
```

For " and \ that should yield the correct result and require less concatentations.

**Comment by delvedor** [comment]
Hey, sorry for the delay!
I'll try your suggestion as soon as I can, unfortunately (or not?) I found a bug that I must solve :P
Thanks!

**Comment by mcollina** [comment]
I think this can be closed, as the referenced PR has been merged.
