### ISSUE TITLE
Rewrite schema dereference to be explicit rather than a side effect of other functions

### ISSUE THREAD

**Issue by paolochiodi** [fastify/fast-json-stringify#241]
## 🚀 Feature Proposal

This is not a regular feature request in that I'm not proposing a new external feature, but rather an internal rewrite.

Current code makes difficult to understand how schema is "dereferenced" (normalised?) because it mostly happen as side effect of functions doing other things.

I propose a rewrite to make the dereference happen explicitly as soon as build is called. 
This is probably less efficient, because schema would be traversed twice, but that would only happen once at build time and the code would be greatly improved, in my opinion.

## Motivation

The schema the build function gets must be dereferenced: every `$ref`s must be replaced with the actual schema they point to.

My understanding is that this is needed for the calls to ajv.validate to work (see here https://github.com/fastify/fast-json-stringify/blob/6da3b3e8ac24b1ca5578223adedb4083b7adf8db/index.js#L1082).
That's because we are passing only a subset of the schema to ajv and any reference to parts of the schema not included in the subset would cause an error.

The problem I see is that dereference is not explicit and is happening inside other functions that are doing other things. In example, the `buildCode` function is also replacing any reference in the object properties of a schema with the actual schema (see https://github.com/fastify/fast-json-stringify/blob/6da3b3e8ac24b1ca5578223adedb4083b7adf8db/index.js#L631).

In my (albeit limited) experience working on https://github.com/fastify/fast-json-stringify/pull/239 I found this makes the code harder to understand because it makes difficult to follow which piece of code modified the schema.
It's also easy to forget to dereference the schema when implementing a new feature and the error that would happen at run time would be far removed from where the dereference should happen.

The current implementation also mutates the schemas passed as input, which may be undesired.

**Comment by mcollina** [comment]
I agree, it would be a good piece of work!
