### ISSUE TITLE
fast-json-stringify mutates input schema

### ISSUE THREAD

**Issue by paolochiodi** [fastify/fast-json-stringify#242]
## 🐛 Bug Report

`fast-json-stringify` mutates the schema passed as input when it contains `$ref`s.

I'm not 100% sure this could be considered a bug because the mutated schema is equivalent to the original one, but I guess this may be undesired in some contexts.

This follows from https://github.com/fastify/fast-json-stringify/issues/241

## To Reproduce

```js
test('input schema is not mutated', (t) => {
  t.plan(3)

  const schema = {
    title: 'object with $ref',
    type: 'object',
    definitions: {
      def: { type: 'string' }
    },
    properties: {
      obj: {
        $ref: '#/definitions/def'
      }
    }
  }

  const clonedSchema = JSON.parse(JSON.stringify(schema))

  const object = {
    obj: 'test'
  }

  const stringify = build(schema)
  const output = stringify(object)

  try {
    JSON.parse(output)
    t.pass()
  } catch (e) {
    t.fail()
  }

  t.equal(output, '{"obj":"test"}')
  t.deepEqual(schema, clonedSchema)
})
```

## Expected behavior

Schema should not be mutated and test should pass.
## Your Environment

- *node version*: 12
- *fastify version*: 2.2.2
- *os*: Mac

**Comment by mcollina** [comment]
I think we should just do a deep clone of the incoming schema.

**Comment by paolochiodi** [comment]
> I think we should just do a deep clone of the incoming schema.

If we decide to implement https://github.com/fastify/fast-json-stringify/issues/241 cloning may be unnecessary

**Comment by Eomm** [comment]
Reopening as I hit this issue today

it could be related to 
https://github.com/fastify/fast-json-stringify/issues/308

**Comment by jonnydgreen** [comment]
I've hit a similar schema mutation issue when providing an external schema through the `fast-json-stringify` options while using `fastify-swagger`. With the following test definition, I would expect the original `$ref` definitions to be preserved in the OpenAPI schema output, but after a bit of digging, it looks like they are being resolved by `fast-json-stringify` mutating the external schema when building the serialisers.

```js
'use strict'

const { test } = require('tap')
const Fastify = require('fastify')
const Swagger = require('swagger-parser')
const fastJsonStringify = require('fast-json-stringify')
const fastifySwagger = require('fastify-swagger')

const openapiOption = {
  openapi: {},
  refResolver: {
    buildLocalReference: (json, baseUri, fragment, i) => {
      return json.$id || `def-${i}`
    }
  }
}

test('should support refs in components definition', async (t) => {
  const fastify = Fastify()
  fastify.register(fastifySwagger, openapiOption)
  fastify.register(async (instance) => {
    const schemas = [
      {
        $id: 'schemaA',
        type: 'object',
        properties: {
          a: { type: 'string' }
        }
      },
      {
        $id: 'schemaB',
        type: 'object',
        properties: {
          e: { $ref: 'schemaA' }
        }
      }
    ]

    for (const schema of schemas) {
      instance.addSchema(schema)
    }

    instance.post('/url', { schema: { response: { 200: { $ref: 'schemaB' } } } }, () => {})
  })

  await fastify.ready()

  const openapiObject = fastify.swagger()
  t.same(openapiObject, {
    openapi: '3.0.3',
    info: {
      version: '6.0.1',
      title: '@fastify/swagger'
    },
    components: {
      schemas: {
        schemaA: {
          type: 'object',
          properties: {
            a: {
              type: 'string'
            },
          }
        },
        schemaB: {
          type: 'object',
          properties: {
            e: {
              // I would expect this to be preserved
              $ref: '#/components/schemas/schemaA'
            }
          }
        }
      }
    },
    paths: {
      '/url': {
        post: {
          responses: {
            200: {
              description: 'Default Response',
              content: {
                'application/json': {
                  schema: {
                    $ref: '#/components/schemas/schemaB'
                  }
                }
              }
            }
          }
        }
      }
    }
  })

  await Swagger.validate(openapiObject)

  t.pass()
})
```

With the above, I get the following error:

<img width="390" alt="Screenshot 2022-05-03 at 23 18 25" src="https://user-images.githubusercontent.com/31290910/166576325-1ed0de9d-e229-488c-a20e-cc7ad81870a0.png">

After defining a custom serialiser that does a basic clone of the inputs in the build phase, it works as expected:

```js
function buildSerializer(externalSchemas, serializerOpts) {
  const opts = Object.assign({}, serializerOpts, { schema: externalSchemas })
  return function responseSchemaCompiler({ schema /* method, url, httpStatus */ }) {
    // Basic cloning during the build phase
    const clonedSchema = JSON.parse(JSON.stringify(schema))
    const clonedOpts = JSON.parse(JSON.stringify(opts))
    return fastJsonStringify(clonedSchema, clonedOpts)
  }
}

test('should support refs in components definition', async (t) => {
  const fastify = Fastify({
    schemaController: { compilersFactory: { buildSerializer } }
  })

  // ...
})
```

It seems like cloning all schema inputs during the build phase would be the best solution, but let me know what you think! I have some time to help resolve this if you need :)

**Comment by mcollina** [comment]
I'm just afraid that all this cloning would lead to massive churn on memory. Anyway I'm afraid it's the only option.

**Comment by jonnydgreen** [comment]
> Before we go there, maybe it's possible to fix this specific case, as I think we already maintain a Map of all the refs.

Makes sense, I'll take a look!
