### ISSUE TITLE
Support schemas defined in separate JSON files in TypeScript

### ISSUE THREAD

**Issue by mattbishop** [fastify/fast-json-stringify#244]
## 🚀 Feature Proposal

I am using external schema json files as recommended for fastify's route definitions as described here: https://www.fastify.io/docs/latest/TypeScript/#json-schema

However, when I attempt to follow the same pattern with fast-json-stringify, I get TypeScript compiler errors stating the imported json schema does not match the types in build.ObjectSchema. I have tried several ways to edit the JSON file to match, including copying it into my source and instantiating it as an object directly (which works), then copying it back out to the JSON file.

I am able to use this pattern of external schema files if I cast the json reference to ObjectSchema like this:

```typescript
import eventResponseSchema from "./schema/get-event-response.json"

const stringifyEvent = fastJson(eventResponseSchema as ObjectSchema)
``` 

## Motivation

Consistent schema usage patterns in fastify.

**Comment by mcollina** [comment]
Are you using this with Fastify?
Anyway, would you like to send a PR to support this?

**Comment by mattbishop** [comment]
Yes with fastify 3.1.1.

**Comment by mattbishop** [comment]
I'm not sure how to roll a PR for this, as the Schema types already defined
are nice and strict, whereas the one in Fastify is basically `unknown`.

**Comment by mcollina** [comment]
I don't really understand the issue. If you are using fastify, you should not be using this module directly.

Maybe @Ethan-Arrowood can help :)

**Comment by mattbishop** [comment]
I'm using this lib to generate ndJson responses, so I have to convert my JS objects to strings directly.

**Comment by Ethan-Arrowood** [comment]
JSON files imported via `import json from 'my-json-file.json'` will have their exact types implied by TypeScript. So the json

```
{
  "foo": "bar"
}
```

will be inferred as the type of `"foo"` to be `string`

**Comment by mattbishop** [comment]
The JSON files I am importing are actually json-schema files, not JSON data files.

**Comment by Ethan-Arrowood** [comment]
Json-schema is still json. The type will not be something generic like ObjectSchema, it'll be specific to whatever is literally in the json file. The `as ObjectSchema` is the correct casting.

**Comment by mcollina** [comment]
So this can be closed?

**Comment by mattbishop** [comment]
I see Ethans's point as well as understand that my use of this lib is a bit of an edge case anyways.

**Comment by Ethan-Arrowood** [comment]
@mattbishop you can look to use something like json-schema-to-typescript or typebox though if you want better type support for your json schemas. Both of those modules have different solution paths so I'd recommend you checkout which would most suite your needs.

If you have any other questions feel free to keep replying here; otherwise you can close the issue!

**Comment by mattbishop** [comment]
I will close it here but I'm wondering if this might be a core fastify feature--schema for response bodies?
