### ISSUE TITLE
Required array not being completely processed

### ISSUE THREAD

**Issue by westsuhanic** [fastify/fast-json-stringify#245]
## 🐛 Bug Report

The required array is not being completely analyzed. If I specify that operation and length are required in a schema via the required field:

required: ['operation','length']

and I do not specify 'length', no exception is thrown. If I omit 'operation' then an exception is thrown as expected.

## To Reproduce

```js
// Paste your code here

const fastJson = require('fast-json-stringify')
const schemaOperation = fastJson({
  title: 'Schema for Operation Specification',
  type: 'object',
  properties: {
    operation: {
      description: 'the operation',
      type: 'string',
      default: 'NotSet'
    },
    length: {
      description: 'the number of characters to specify the operation',
      type: 'integer',
      default: -9999
    }
  },
  required: ['operation','length']
})

const opName = 'biotiffPopulate';
const opNameLength = opName.length;
const tmp = schemaOperation({
  operation: opName,
  //length: opNameLength
});

var ttt = JSON.parse( tmp );
console.log( ttt.operation );
console.log( ttt.length );
console.log( ttt );
```

## Expected behavior

```js
if length is not specified then I expect the following:
undefined:173
        if (obj[required[i]] === undefined) throw new Error('"' + required[i] + '" is required!')
                                            ^

Error: "length" is required!
```

## Your Environment

- *node version*: 10.19.0
- *fast json stringify version*: >=2.2.3
- *os*: Linux

**Comment by Eomm** [comment]
You have defined a `default` value for `length`, for this reason it is not throwing.

I think that code should not throw when `operation` is missing even, due the `default: NotSet`.. that seems a bug
