### ISSUE TITLE
Mandatory items for type array - v1.x

### ISSUE THREAD

**Issue by Eomm** [fastify/fast-json-stringify#247]
## 🐛 Bug Report

When the `type: array` doesn't have the `items` specified an error is thrown.

## To Reproduce

```js
var fjs = require("fast-json-stringify@1.21.0")

fjs({
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "equipments": {
      "type": "array"
    }
  }
})
```

## Expected behavior

Not throws and based on the standard:

> By default, the elements of the array may be anything at all. However, it’s often useful to validate the items of the array against some schema as well. This is done using the items, additionalItems, and contains keywords.

## Your Environment

- *node version*: 12
- *fast-json-stringify version*: >=1.21.0
- *os*: Mac, Windows, Linux

I will work on a fix

**Comment by mcollina** [comment]
Is this a problem on v2 as well?

**Comment by Eomm** [comment]
> Is this a problem on v2 as well?

Nope, it works on v2.
I will add a test there if it is missing
