### ISSUE TITLE
null array value throws TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by bburke4** [fastify/fast-json-stringify#249]
## 🐛 Bug Report

When a null value is expected to be an array it throws `TypeError: Cannot read property 'length' of null`. 

This looks very similar to: https://github.com/fastify/fast-json-stringify/issues/218

I love fast-json-stringify and fastify. Thanks a lot!

## To Reproduce

```js
const fastJson = require('fast-json-stringify');

fastJson({
  type: 'object',
  properties: {
    arr: {
      type: 'array',
      items: {
        type: 'number'
      }
    }
  }
})({ arr: null })
```
```
Uncaught TypeError: Cannot read property 'length' of null
    at $arr$mainarr (eval at build (/Users/b.burke/dev/play/node_modules/fast-json-stringify/index.js:158:20), <anonymous>:144:17)
    at $main (eval at build (/Users/b.burke/dev/play/node_modules/fast-json-stringify/index.js:158:20), <anonymous>:132:17)
```

Putting the 'array' type in an array yields different results...
```js
fastJson({
  type: 'object',
  properties: {
    arr: {
      type: ['array'],
      items: {
        type: 'number'
      }
    }
  }
})({ arr: null });

'{"arr":null}'
```

using `undefined` rather than `null` yields different results...
```js
fastJson({
  type: 'object',
  properties: {
    arr: {
      type: 'array',
      items: {
        type: 'number'
      }
    }
  }
})({ arr: undefined });

'{"arr":null}'
```

## Expected behavior

I would expect it to either print 'null' or coerce it to an empty array. I tried setting `default: []` but it didn't make a difference. setting `type: ['array', 'null']` does make it print null instead.

## Your Environment

- *node version*: v12.16.1
- *fastify version*: 2.2.3
- *os*: Mac

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by alemagio** [comment]
Hi, is anyone working on this?

**Comment by mcollina** [comment]
Maybe yourself! :P
