### ISSUE TITLE
object properties support any type

### ISSUE THREAD

**Issue by jamieYou** [fastify/fast-json-stringify#250]
```
obj = {
  a: '', b:'',
  data: {
    title: 'abc'
  }
}

obj = {
  a: '', b:'',
  data: {
    desc: 'abc'
  }
}
```
`obj.data` is a object, but properties is any。

Is it currently supported?

**Comment by mcollina** [comment]
I do not understand the question.

**Comment by L2jLiga** [comment]
As I understand you want to have object with any keys, if so then you can use [additional properties](https://github.com/fastify/fast-json-stringify#additional-properties) and if they can be any type then [anyOf](https://github.com/fastify/fast-json-stringify#anyof) can help.

**Comment by fox1t** [comment]
Let me give it a shot to decipher this issue: @jamieYou are you talking about TypeScript `any`?

**Comment by jamieYou** [comment]
> Let me give it a shot to decipher this issue: @jamieYou are you talking about TypeScript `any`?
