### ISSUE TITLE
Stringify fails with multiple defaults

### ISSUE THREAD

**Issue by gabemeola** [fastify/fast-json-stringify#251]
## 🐛 Bug Report

Stringifying fails when using multiple defaults + required.  This isn't the case when using AJV directly.  
You can run it here: https://repl.it/@gabemeola/fast-json-stringify-default-issue  

Removing `required` passes but isn't the intended schema.  
Removing all but one `default` and `required` does pass as intended. 
e.g.  
```
const schema = {
  type: 'object',
  properties: {
    name: {
      default: 'Person',
      type: 'string',
    },
  },
  required: [
    'name',
  ]
}

```

## To Reproduce

```js
const fastJson = require('fast-json-stringify')
const Ajv =  require('ajv')

const ajv = new Ajv({ useDefaults: true });

const schema = {
  type: 'object',
  properties: {
    name: {
      default: 'Person',
      type: 'string',
    },
    dev: {
      type: 'boolean',
      default: false,
    }
  },
  required: [
    'name',
    'dev'
  ]
}

const validate = ajv.compile(schema);
const str = fastJson(schema)

console.log("AJV Passed:", validate({}))
console.log(str({})) // Error: "name" is required!
```

## Expected behavior

```js
{ "name": "Person", "dev": false }
```

## Your Environment

- *node version*: 12
- *fastify version*: 2.2.3

**Comment by Eomm** [comment]
Yeah, it is definitely a [bug](https://runkit.com/embed/9n39lo3v797d)!

Would you like to send a Pull Request to address this issue?
