### ISSUE TITLE
Failed building the serialization schema when it is a typebox object with an "any" type

### ISSUE THREAD

**Issue by JSteunou** [fastify/fast-json-stringify#255]
## 🐛 Bug Report

When using a valid schema with a property define as an `any` kind of type, `{}` in json schema (without enforced type), fastify just crash 

## To Reproduce

Add a response schema with something like

```js
{
  schema: {
    response: {
      200: {type: "object", properties: {foo: {}}}
    }
  }
}
```
note the absence of `type` for property `foo`

## Expected behavior

```log
FastifyError [Error]: Failed building the serialization schema for GET: /foos, due to error undefined unsupported
,    at Boot.emit (events.js:327:22)
,    at Boot.<anonymous> (/project/node_modules/fastify/lib/route.js:280:19)
,    at Object.onceWrapper (events.js:421:28)
,    at /project/node_modules/avvio/boot.js:153:12
,    at /project/node_modules/avvio/plugin.js:269:7
,    at done (/project/node_modules/avvio/plugin.js:201:5)
,    at check (/project/node_modules/avvio/plugin.js:225:9)
,    at internal/process/task_queues.js:153:7
,    at AsyncResource.runInAsyncScope (async_hooks.js:186:9)
,    at AsyncResource.runMicrotask (internal/process/task_queues.js:150:8) {
,  code: 'FST_ERR_SCH_SERIALIZATION_BUILD',
,  statusCode: 500
,}
```

Ajv validation as input works fine, schema is valid, serialisation should be fine too.

## Your Environment

- *node version*: 12 LTS
- *fastify version*: ^3.3.0
- *os*: Linux
- *any other relevant information*

**Comment by JSteunou** [comment]
Very similar to #253

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by JSteunou** [comment]
I started to add unit tests and did not succeed to reproduce the issue.

After many times digging around, it seems the culprit might be the lib generating the schema, because using old trick like `JSON.parse(JSON.stringify(schema))` produce a valid schema with no fastify errors.

@fox1t it seems you are using the same library https://github.com/sinclairzx81/typebox did you ever encounter the same issue?

**Comment by Eomm** [comment]
Yes, we should manage this case as the issue you linked: when a type is missing the default should be `object` with `additionalProperties: true` (if is not defined)

To fix it you should remove the `enum` check from this #254 PR, you could take inspiration from that one to add new tests 👍

**Comment by JSteunou** [comment]
@Eomm I might rename the issue title because like I said above I cannot reproduce the issue with unit tests with simple object because the issue is really tight to the use of [typebox](https://github.com/sinclairzx81/typebox)

The object created by *typebox* are complex. I could not tell if it is a bug or a feature but in some condition, not always, the schema object needs to be JSON stringify and parse back as object before used with *fast-json-stringify*

If this lib claims to only be compatible with simple object then it is ok but if it should be compatible with complex structure having some prototype, methods, ... then it is a bug.

**Comment by mcollina** [comment]
I would recommend to adjust the title and description of this issue with mentions to Typebox.

We do not claim to be compatible with I would recommend sending a PR with a fix and unit tests. There might be some checks that are missing, maybe a `hasOwnProperty` somewhere.

**Comment by fox1t** [comment]
@JSteunou yes I am using it. That issue pops up when `type: ` is missing from the generated object. The more basic repro was to make and `enum`: typebox generate it without specifying the `type` since an `enum` can have as many types as it needs. This issue, however, it was fixed by @Eomm PR.

Speaking of this issue: can you make a repro repository that uses typebox so we can inspect the generated schema and see what we are lacking to support? Typebox should generate always valid schemas.

**Comment by JSteunou** [comment]
Yup I would try this in the day. Another thinking I just had is that input validation works, so ajv accept the schema as typebox object just fine. It is the serialisation part that made it crash.

**Comment by fox1t** [comment]
> Yup I would try this in the day. Another thinking I just had is that input validation works, so ajv accept the schema as typebox object just fine. It is the serialisation part that made it crash.

Exactly. It is just a fast-json-stringify issue. We need to find it and fix it :)

**Comment by JSteunou** [comment]
Here it is https://github.com/JSteunou/fast-json-stringify/commit/aa8272b5e58730ad6ed7136ab6e0f28c038fcb22 ;)

**Comment by thatsnotright** [comment]
We hit this issue with TypeBox, but as well by importing all the JSON schemas from https://github.com/axa-ch/json-logic-js/pull/4/files via fastify.addSchema and `
{
        schema: {
          body: { $ref: 'http://jsonlogic.com/schemas/json-logic.json' },
          response: GET_RESPONSE_SCHEMA,
        },
      },`

so it's not specific to typebox.

**Comment by mcollina** [comment]
@thatsnotright this still need a PR to fix it :)

**Comment by sinclairzx81** [comment]
@mcollina This issue should be resolved with the https://github.com/fastify/fast-json-stringify/pull/283 PR. 

@JSteunou Are you able to test for this your side to confirm?

**Comment by JSteunou** [comment]
@sinclairzx81 sorry not at the moment :(
