### ISSUE TITLE
Empty object patternProperties throws "undefined unsupported"

### ISSUE THREAD

**Issue by fox1t** [fastify/fast-json-stringify#259]
## 🐛 Bug Report

This schema thorws `Failed building the serialization schema for ##route##, due to error undefined unsupported`
```json
{
  "type": "object",
  "additionalProperties": false,
  "patternProperties": {
    "^[a-z]{2}_[A-Z]{2}$": {}
  },
  "properties": {
    "default": {}
  }
}
```
~The part that makes the package throwing is~
```js
//"patternProperties": {
//    "^[a-z]{2}_[A-Z]{2}$": {}
//  }
```
EDIT: after 1 hour of digging the actual part that is throwing is: 
```json
 "properties": {
    "default": {}
  }
```

Because it searcheas for `type` property in ~`"^[a-z]{2}_[A-Z]{2}$": {}`~ default and doesn't find anything. In addtion to that 
`"default": {} ` fails this check https://github.com/fastify/fast-json-stringify/blob/b59248277be1b36f265ba548ad39da718553b3fb/index.js#L1178 because in the real value is `"default":{$id: undefined}`. In fact `schema.hasOwnProperty('$id')` returns `true`!

On the other hand `"^[a-z]{2}_[A-Z]{2}$": {}` remains an empty object on the check.

## To Reproduce
Run a fastify server and use 
```
{
  "type": "object",
  "additionalProperties": false,
  "patternProperties": {
    "^[a-z]{2}_[A-Z]{2}$": {}
  },
  "properties": {
    "default": {}
  }
}
```
as response schema.

## Expected behavior

Assigning any to every prop that matches "^[a-z]{2}_[A-Z]{2}$" pattern or throw a better message.

## Your Environment

- *node version*: 14
- *fastify version*: 3.4.1
- *os*: Mac

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by fox1t** [comment]
Sure. Any hints on where to look?

**Comment by fox1t** [comment]
I am digging into this and this could be also a fastify issue. If so, I'll move this to the proper repository and add more info.

**Comment by fox1t** [comment]
I am flagging this as invalid for the moment. I need more investigation on this.

**Comment by fox1t** [comment]
Finally manage to debug this properly. I am leaving this comment both as a future reference and to find if this needs to be fixed. 

This turned out to be a problem related to fluent-schema/fast-json-stringify interaction. 

Fluent-schema adds a `$id: undefined` property when you pass an empty fragment (`.raw({}`) to `.prop(` and this additional prop makes https://github.com/fastify/fast-json-stringify/blob/b59248277be1b36f265ba548ad39da718553b3fb/index.js#L1178 fail on the fast-json-stringify. 
For example this schema:

```js
S.object()
  .additionalProperties(false)
  .prop('value')
  .required()
  .extend(
    S.object()
      .additionalProperties(false)
      .prop('catalogCode', S.string())
      .required()
      .prop(
        'locales',
        S.object()
          .additionalProperties(false)
          .patternProperties({
            '^[a-z]{2}_[A-Z]{2}$': S.raw({}), // <- this doesn't anything
          })
          .prop('default', S.raw({})), // default becames `{$id: undefined}`
      )
      .required(),
  )
```


@mcollina do you think we could add another check here on the isEmpty to consider also this case and make the function return true? `{$id: undefined}` will be stripped anyway during the serialization since its value is `undefined`.

**Comment by mcollina** [comment]
Yes, go for it. This seems legit.
