### ISSUE TITLE
Pre stringified JSON

### ISSUE THREAD

**Issue by artur-ma** [fastify/fast-json-stringify#261]
## 🚀 Feature Proposal

Pre stringified JSON type, in case I already have stringified JSON that I want to interpolate in another object 

## Motivation

Since this lib aims to optimize performance in cases when it really matters, I think it is good to save extra CPU time by prevent prsing and stringifying the JSON again.

## Example

in my code I have 
```
// response will be stringified json: '{ "id": "awsomeUserId", "name": "myName" }'
const stringifiedJsonResponse = axios.get('https://myservice.com/api/user/:id');
```

current solution 

```
const parsedUser = JSON.parse(stringifiedJsonResponse);

const stringify = fastJson({
  type: 'object',
  properties: {
     user: {
       type: 'object',
       properties: {
           id: { type: 'string' },
           name: { type: 'string' }
       }
     },
    posts_count: { type: 'number' } 
});

const result = stringify({
   user: parsedUser
   posts_count: 5
});
```

proposed solution

```
const stringify = fastJson({
  type: 'object',
  properties: {
    user: { type:'placeholder' }
    posts_count: { type: 'number' } 
});

const result = stringify({
   posts_count: 5
}, { user: stringifiedJsonResponse } );
```

In this case I will save a call for `JSON.parse` and some CPU usage on `fast-json-stringify` that will have to stringify it.

**Comment by jsumners** [comment]
I don't understand. You can't simply define `{ user: { type: 'string' } }`?

This library interprets spec compliant JSON Schema. See https://json-schema.org/. That spec does not specify a `{type: 'placeholder'}`.

**Comment by mcollina** [comment]
Overall I would be ok with supporting an extension, as most libraries do. Doing this would give us a significant boost at it would safe a decoding/encoding cycle at the cost of safety, i.e. the resulting payload might not be following the schema.

I'm also not 100% of how I would design this API-wise, so maybe it would take a couple of iteration to finalize. Would you like to work on a PR?

**Comment by artur-ma** [comment]
@jsumners 
> I don't understand. You can't simply define `{ user: { type: 'string' } }`?
> 
> This library interprets spec compliant JSON Schema. See https://json-schema.org/. That spec does not specify a `{type: 'placeholder'}`.

Plase see my example, I already have a JSON that is stringified, if I will put it in "string" field it will escape and and it would be string inside a json, but I want it as JSON inside JSON 

example 

```
// will hold this string: '{ "id": "awsomeUserId", "name": "myName" }'
const user = JSON.stringify({ id: 'awsomeUserId', name: 'myName' }) //asume I get it from externam API

const stringify = fastJson({
  type: 'object',
  properties: {
    user: { type:'string' },
    posts_count: { type: 'number' } 
  }
});
```
// will result: 
// '{"user":"{\\"id\\":\\"awsomeUserId\\",\\"name\\":\\"myName\\"}","posts_count":8}'
// but I want it to be:  '{"user":{"id":"awsomeUserId","name":"myName"}, "posts_count":8}'
stringify({ user, posts_count: 8 });
```

I hope it is clear now.

@mcollina Im new at this codebase, will try to do my best to  conclude it  in some PR

**Comment by Eomm** [comment]
As an option, there is the media type field: https://json-schema.org/understanding-json-schema/reference/non_json_data.html

Supporting

```
Type: object
ContentMediaType: "application/json"
```
It Would not be standard (since media type works with strings type), but it seems clearer then `placeholder ` to me 

Of course a plugin system would be even better

**Comment by fox1t** [comment]
I am not sure that adding a new DSL is a good choice here :/
