### ISSUE TITLE
enum values are not handled well by the serializer

### ISSUE THREAD

**Issue by iMoses** [fastify/fast-json-stringify#274]
## 🐛 Bug Report

When using enum in a json schema the serialization results turn string values in an array/object of chars.

## To Reproduce

https://codesandbox.io/s/fastify-2707-forked-47hkd

```js
const fastJson = require("fast-json-stringify");
const stringify = fastJson({
  title: "Example Schema",
  type: "object",
  properties: {
    order: {
      enum: ["asc", "desc"]
    }
  }
});
console.log(
  stringify({
    order: "asc"
  })
); // output: {"order":{"0":"a","1":"s","2":"c"}}
```

## Expected behavior

Should return the value of the enum without any modifications.

```js
console.log(
  stringify({
    order: "asc"
  })
); // should output: {"order":"asc"}
```

## Your Environment

- *node version*: 14
- *fastify version*: >=3.8.0
- *os*: Linux

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by iMoses** [comment]
> Would you like to send a Pull Request to address this issue? Remember to add unit tests.

I haven't investigated it enough to understand why this is happening. 
I'll try to clear up time for it, but any input on where to look can be helpful here as i don't have too much free time on my hands :)

**Comment by iMoses** [comment]
@mcollina I found the issue [here](https://github.com/fastify/fast-json-stringify/blob/master/index.js#L169) but i'm not sure how this should be handled.

Seems that `enum` is defined as an `objectKeywords` meaning it will be recognize as an object and that's why the string is breaking down. If moved to the `stringKeywords` array the problem is solved, but then it will only work in case the `enum` is a string. Although I'm not sure it should, because it isn't part of json schema, adding a `type: 'string'` does help as the inferred type check never happens this way.

This also opens another bug/feature that I'm not sure how you want to handle, which is that enum values are not validated at all. Seems to me that if the serializer fails when passing it a string instead of an array then it should also fail when passing it `100` for an enum that takes only `10`.

I think a better way is needed here in order to handle enum, as it is possible to use multiple types and it requires a special kind of validation. WDYT?

**Comment by mcollina** [comment]
See https://json-schema.org/understanding-json-schema/reference/generic.html#enumerated-values. It seems we should have some logic to detect the value at runtime and adapt accordingly, maybe using some deep equality logic.

**Comment by Eomm** [comment]
This is related to #254 

The string is treated like and object and this can be improved 👍

**Comment by lazharichir** [comment]
@iMoses facing the very same issue with my `enum` of strings without a type. Have you started anything on this issue? Keen to help.

**Comment by mcollina** [comment]
Go for it!

**Comment by KiraPC** [comment]
@mcollina @Eomm 

I'm trying to fix this issue.

After a minimum of debug, I figured out that reverting the changes introduced by https://github.com/fastify/fast-json-stringify/pull/254 the case described by this issue works, but also the tests introduced by Eomm in 254 works too.

So, do I'm missing something?

**Comment by mcollina** [comment]
I will recommend you to open a PR, it's the simplest way to review a change.

Please add a new test to cover this case.
