### ISSUE TITLE
Support "const" keyword

### ISSUE THREAD

**Issue by L2jLiga** [fastify/fast-json-stringify#275]
## 🐛 Bug Report

fast-json-stringify throw error when trying to compile schema with `const` keyword:

undefined unsupported

## To Reproduce

```js
const schema = {
  "type": "object",
    "properties": {
      "foo": { "const": "bar" }
    }
}

fastJSON(schema);
```

## Expected behavior

Schema compiles successfuly

## Your Environment

- *node version*:  n/a
- *fast-json-stringify*: latest master
- *os*: n/a
- *any other relevant information*

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Eomm** [comment]
What is expected?

An AJV validation with `const` would mean that the `foo` property if exists, it must be `bar` otherwise an error will throw an error

For serialization: should we throw an error if an existing property is not that `const` or force the value?

**Comment by L2jLiga** [comment]
I think behavior should be same

**Comment by L2jLiga** [comment]
I'm going to work on it today
