### ISSUE TITLE
Integer are not truncated

### ISSUE THREAD

**Issue by Eomm** [fastify/fast-json-stringify#277]
## 🐛 Bug Report

This script:

```js
const fjs = require("fast-json-stringify")
const serial = fjs({
  type: 'object',
  properties: { foo: { type: 'integer' } }
})
console.log(serial({ foo: 1.2 }))
```

Produces: `{"foo":1.2}`

## Expected behavior

A truncated integer: `{"foo":1}`

I think a rounding function could be provided as input aswell like:

```
const serial = fjs({
  type: 'object',
  properties: { foo: { type: 'integer' } }
}, { rounding: Math.floor } )
```

Do you have any thought on this?

## Your Environment

- *fast-json-stringify*: 2.3.0

**Comment by mcollina** [comment]
Go ahead and send a PR!
