### ISSUE TITLE
Typebox and `fast-json-stringify` - union doesn't work inside array

### ISSUE THREAD

**Issue by L2jLiga** [fastify/fast-json-stringify#279]
@sinclairzx81 I've just tested this using Typebox and `fast-json-stringify` (via `fastify`) and found the following behaviour:

```js
export const CurrencyKind = Type.Union([
  Type.Literal('AED'),
  Type.Literal('AUD'),
  Type.Literal('BRL'),
  Type.Literal('CAD')
... etc
```

This now works with your PR above:
```js
const UsersBidUpdateOutput = Type.Object({
  id: Type.String(),
  currency: CurrencyKind,
  stripe_id: Type.String(),
})
```

But this one doesn't:
```js
const UserCouponsOutput = Type.Array(
  Type.Object({
    code: Type.String(),
    currency: CurrencyKind,
    amount_off: Type.String(),
    percent_off: Type.String(),
    valid: Type.Boolean(),
  })
)
```

Presumably because it's an Array of objects where one of the properties is the union of literals.

_Originally posted by @toddheslin in https://github.com/fastify/fast-json-stringify/issues/271#issuecomment-755887885_

**Comment by sinclairzx81** [comment]
@Hi,

I've just submitted a PR that should resolve this https://github.com/fastify/fast-json-stringify/pull/280. Will need to wait on the `fast-json-stringify` maintainers to give the greenlight. Thanks for letting me know. 

S

**Comment by sinclairzx81** [comment]
@L2jLiga Hi, This issue should be resolved with PR https://github.com/fastify/fast-json-stringify/commit/400774ad5846e2545ca958a001a926e92e1860f9. Are you able to confirm your side? Also, cc @mcollina
