### ISSUE TITLE
Support for JSON Typedef?

### ISSUE THREAD

**Issue by ucarion** [fastify/fast-json-stringify#287]
## 🚀 Feature Proposal

Today, this package supports a subset of [JSON Schema](https://json-schema.org/). This feature proposal is for adding support for (the entirety of) [JSON Type Definition](https://jsontypedef.com/).

## Motivation

JSON Type Definition is an RFC that's rather similar to JSON Schema. Being able to support it in its entirety would be nice from a documentation and interoperability standpoint, because users don't have to face the issue of different tools supporting different subsets of the specification. The fast-json-stringify spec could state flatly that it supports the entire spec, no questions asked.

More concretely, if fast-json-stringify supports JSON Type Definition, then existing code which relies on [TypeScript types generated from JSON Typedef schemas](https://jsontypedef.com/docs/typescript-codegen/) could then enjoy optimized stringify methods for their types.

Hypothetically, we could even extend this to an optimized JSON.parse as well. Perhaps I should create a separate issue for this? I don't know if JSON Schema's feature set is part of the picture of why there isn't a fast-json-parse or some such, so I don't know if the schema languages supported is a question that's separable from the question of whether it's possible to write a type-optimized JSON.parse.

## Example

Very hypothetically, something like:

```js
const fastJson = require('fast-json-stringify')
const stringify = fastJson({ "properties": { "foo": { "type": "string" }}}, { schemaType: "jtd" })

// ...
```

**Comment by mcollina** [comment]
Would this pull in additional dependencies?

**Comment by ucarion** [comment]
Would it be possible for us simply say that fastJson returns a function whose behavior is undefined if the input is invalid against the schema (or maybe just throws a generic "bad input" exception), at least if you're using the JSON Typedef mode?

That way, people who are validating inputs with JSON Typedef, and then use TypeScript in a sound way end-to-end don't have to pay for extra validation?

And for folks who aren't sure if their data is valid against the schema they're passing in, they can use an existing JSON Type Definition implementation, like the `ajv` or `jtd` packages, before they pass it into fast-json-stringify?

**Comment by mcollina** [comment]
> Would it be possible for us simply say that fastJson returns a function whose behavior is undefined if the input is invalid against the schema (or maybe just throws a generic "bad input" exception), at least if you're using the JSON Typedef mode?

Ideally yes, as long as the complexity in the codebase stays in current levels (bugs are not really manageable already).

> That way, people who are validating inputs with JSON Typedef, and then use TypeScript in a sound way end-to-end don't have to pay for extra validation? In a way, a big part of what's nice about JSON Typedef is that when you generate your types from JTD schemas, you can use a JTD validator as a way to work around TypeScript's type erasure at the JSON-to-TypeScript boundary.

This is not clear. The only things that we are validating is the schema itself, which only effect start up time of an application. Or are you referring to something else? 

> And for folks who aren't sure if their data is valid against the schema they're passing in, they can use an existing JSON Type Definition implementation, like the ajv or jtd packages, before they pass it into fast-json-stringify?

This is not clear. We are not validating data.

**Comment by ucarion** [comment]
> This is not clear. The only things that we are validating is the schema itself, which only effect start up time of an application. Or are you referring to something else?

> This is not clear. We are not validating data.

Ah, yeah I see that now. My bad! I misunderstood what gets validated and when.

**Comment by ucarion** [comment]
Actually, hold on, what about stuff like this?

https://github.com/fastify/fast-json-stringify/blob/8681de05b2cd73a014e4bf93cab6193ea1a7d06f/index.js#L774

I would call this validation, and it's validation performed within the generated code. Is this just an exception to the rule?

**Comment by mcollina** [comment]
It's not spec compliant or aim to be. It does a few checks where it is sensible to do so and just that.

The two option with a missing field marked required are to ignore and throw.. and throw is the sensible option.

**Comment by mcollina** [comment]
@ucarion do you plan to work on this?
