### ISSUE TITLE
oneOf with $ref mutate the schema

### ISSUE THREAD

**Issue by Eomm** [fastify/fast-json-stringify#289]
## 🐛 Bug Report

The `oneOf` keyword is replaced with the schema

Causes https://github.com/fastify/fastify/issues/2901

## To Reproduce

```js
const fjs = require('fast-json-stringify')

const reusedSchema = {
  $id: 'example2',
  type: 'object',
  properties: {
    name: {
      oneOf: [{ $ref: 'example1' }]
    }
  }
}

fjs(reusedSchema, {
  schema: {
    example1: {
      $id: 'example1',
      type: 'object',
      properties: {
        name: { type: 'string' }
      }
    }
  }
})

console.log(JSON.stringify(reusedSchema, null, 2))

```

## Expected behavior

`reusedSchema` should not change

## Your Environment

- *node version*: 12
- *fastify version*: >=3.10.0
- fast-json-stringify: 2.4.2

**Comment by Eomm** [comment]
Found these comment on code:

https://github.com/fastify/fast-json-stringify/blob/8681de05b2cd73a014e4bf93cab6193ea1a7d06f/index.js#L1162-L1168

Not sure how to solve:

- `delete schema.$id` solve the (fastify) issue but it would mutate the external schema as well
- clone the external schema only if it has the `$id` keyword (in fastify all the external schemas have it)
- start a great rework where the `$ref` is evaluated JIT and it is not necessary to resolve all the `ref`s before generating the validation function

Thought?

**Comment by mcollina** [comment]
How about we do a full copy when we enter `dereferenceOfRefs()`?

**Comment by Eomm** [comment]
> How about we do a full copy when we enter dereferenceOfRefs()? 

I think it could have trouble when there is a `$ref` inside an external schema, I can try 👍
