### ISSUE TITLE
Any plans to add support replacer functionality?

### ISSUE THREAD

**Issue by Mika83AC** [fastify/fast-json-stringify#301]
Hello eveyone,

I'd like to know if there are plans to add the native JSON.stringifys replacer() functionality like:

`JSON.stringify(input, (key, value) => value instanceof Set ? [...value] : value)`

So it would also be possible to stringify objects which contains Set()s, Map()s, and so on.

Regards,
Michael

**Comment by mcollina** [comment]
There aren't any plans to do so. That being said, I think it might be possible to add support for those natively to objects and arrays respectively.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by onbit-syn** [comment]
Hey, @mcollina,

I am a great fan of Fastify and now I am actively using it on my projects. Please assign this task to me. It will be my pleasure to be a part of such a great product and organisation.

I will also include unit tests. I like this issue and I really want to contribute to it.

**Comment by TommyDew42** [comment]
@onbit-uchenik Is Anubhav still working on this issue? If not, I am more than happy to help! 😌

**Comment by Uzlopak** [comment]
I dont think so. I you want to provide a PR, just do it.

**Comment by TommyDew42** [comment]
@mcollina 
> I think it might be possible to add support for those natively to objects and arrays respectively.

Do you mean we do the following:
* `Set` & `WeakSet`: treat them as an object
* `Map` & `WeakMap`: treat them as an array

**Comment by mcollina** [comment]
You can do Set and Map, not their weak counterparts.

**Comment by TommyDew42** [comment]
Wanna confirm what we want. Is the type of `Set` in the schema `set` or `object`? The same question to `Map` too.

**Comment by Uzlopak** [comment]
Imho Set is Array and map is object

**Comment by mcollina** [comment]
Indeed, yes.

**Comment by TommyDew42** [comment]
I didn't expect this issue would be this complicated. I have closed my PR #545. Feel free to work on this issue if you are interested!

**Comment by captainrdubb** [comment]
sooo, can we get the replacer?

**Comment by mcollina** [comment]
After two years, this is unlikeky to happen. I won't be opposed to a PR, but there seem no interest in implementing this by its maintainers or users.
