### ISSUE TITLE
Benchmark against Ajv JTD serializer

### ISSUE THREAD

**Issue by mcollina** [fastify/fast-json-stringify#306]
## 🚀 Feature Proposal

Add a benchmark against Ajv JTD serializer: https://ajv.js.org/guide/getting-started.html#parsing-and-serializing-json

**Comment by mcollina** [comment]
cc @epoberezkin

**Comment by epoberezkin** [comment]
I can do it in April - thank you @mcollina

**Comment by mcollina** [comment]
Please write this against the `next`  branch, as it already Ajv v7.
