### ISSUE TITLE
optional dependency long should actually be required

### ISSUE THREAD

**Issue by aruniverse** [fastify/fast-json-stringify#314]
## 🐛 Bug Report

I am using fastify in a repo with yarn v2 (berry) and using the zero-install feature which is stricter with dependency management. 

During compilation i get the following error:
```
(node:1536) [MODULE_NOT_FOUND] Error: debug tried to access supports-color (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
 > pnp:C:\Users\ArunG\Repos\GH\gazo\.yarn\cache\fast-json-stringify-npm-2.5.3-5f61461930-b6d1204da2.zip\node_modules\fast-json-stringify\index.js:15:19: error: [@yarnpkg/esbuild-plugin-pnp] fast-json-stringify tried to access long, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: long (via "long")
Required by: fast-json-stringify@npm:2.5.3 (via C:\Users\ArunG\Repos\GH\gazo\.yarn\cache\fast-json-stringify-npm-2.5.3-5f61461930-b6d1204da2.zip\node_modules\fast-json-stringify\index.js)

    15 │   isLong = require('long').isLong
```

Saw `fast-json-stringify` was a sub dep of `fastify`
![image](https://user-images.githubusercontent.com/11051042/114121670-c3222300-98bc-11eb-9e4e-cb35175cd923.png)

I see you guys try to handle this with the try catch block but i think itd be easier if you guys had a direct dependency on the `long` package
![image](https://user-images.githubusercontent.com/11051042/114121857-22803300-98bd-11eb-94a4-e43e75985dbd.png)
![image](https://user-images.githubusercontent.com/11051042/114122000-6d01af80-98bd-11eb-97ab-a40e62d8b1be.png)

I was able to get around this issue using a feature in berry to correct dependencies, [see](https://yarnpkg.com/configuration/yarnrc#packageExtensions), but thought of raising this issue as more and more users will start using pnp.

## To Reproduce

If you need a sample to reproduce this, let me know.

## Proposal

Move ` long` from being a devDep to a direct dep.

## Your Environment

- *node version*: 12.16.2
- *fastify version*: ^3.12.0
- *os*: Windows,
- *yarn*: 2.4.1

**Comment by aruniverse** [comment]
Bump

**Comment by aruniverse** [comment]
Bump

**Comment by climba03003** [comment]
There is no `long` as dependency anymore.
