### ISSUE TITLE
Additional Items is not working

### ISSUE THREAD

**Issue by ajotaos** [fastify/fast-json-stringify#321]
## 🐛 Bug Report

The additional items modifier is causing the module to fail for tuples. AJV works with the schema but fjs fails with the same schema and data.

## To Reproduce

```js
const fast = require('fast-json-stringify');
const serialize = fast({
      type: 'object',
      properties: {
        code: { type: 'string', const: 'BAD_REQUEST' },
        path: {
          type: 'array',
          items: [
            {
              type: 'string',
              enum: ['headers', 'params', 'querystring', 'body']
            }
          ],
          additionalItems: true
        },
        reason: { type: 'string', minLength: 1 }
      },
      required: ['code', 'path', 'reason'],
      additionalProperties: false
    });

serialize({
  "code": "BAD_REQUEST",
    "path": [
      "body",
      "query"
    ],
    "reason": "should be graphql source"
  });
```

## Expected behavior

Expected the serialization to occur, but the `path` schema fails if `additionalItems` is `true` or `{ type: 'string'}`.

## Your Environment

- *node version*: v15.14.0
- *fastify version*:3.14.2
- *os*: Mac

**Comment by mcollina** [comment]
I have a feeling we never implemented this. 
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by KiraPC** [comment]
@mcollina Can this issue be closed by https://github.com/fastify/fast-json-stringify/pull/322?

@ajotaos Could you check now?
