### ISSUE TITLE
rounding not working in properties

### ISSUE THREAD

**Issue by Eomm** [fastify/fast-json-stringify#329]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.x

### Node.js version

14

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

The `rounding` options does not apply on properties `integer`s

### Steps to Reproduce

```js
const fastJson = require('fast-json-stringify')
const stringify = fastJson({ type: 'object', properties: { magic: { type: 'integer' } } }, { rounding: 'ceil' })

console.log(stringify({magic: 4.2}))
// should show "5"
```

### Expected Behavior

should show "5"

The issue is on this code block
https://github.com/fastify/fast-json-stringify/blob/2cc2b8a83679688127f97b6ef1fc0e327e5914fb/index.js#L728

the `$asInteger` is not called at all

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue. can you guide me in what changes need to me made?

**Comment by mcollina** [comment]
In the code block linked above, you should call `$asInteger`.

**Comment by Eomm** [comment]
> Hi, i would like to work on this issue. can you guide me in what changes need to me made?

Sorry if I wrote a PR, but I need this fix next week 😥

**Comment by himanshu007-creator** [comment]
> > Hi, i would like to work on this issue. can you guide me in what changes need to me made?
> 
> Sorry if I wrote a PR, but I need this fix next week 😥

No problem, ⚡
