### ISSUE TITLE
Webpack renames $asBoolean and friends, causing generated code to fail with "$asBoolean is not defined"

### ISSUE THREAD

**Issue by diwic** [fastify/fast-json-stringify#338]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.14.1

### Node.js version

14.17

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

I'm trying to package a fastify application with webpack (without externalizing fastify or fast-json-stringify, we need the final code to be all included in a single .js file).
This worked well until I changed from development to production mode in webpack. Now webpack renames `$asBoolean` to a shorter name, so that the generated code no longer compiles.

### Steps to Reproduce

Create these files:

index.js:
```
const fastJson = require('fast-json-stringify')
const stringify = fastJson({
  title: 'Example Schema',
  type: 'object',
  properties: {
    valid: { type: 'boolean' }
  }
}, { debugMode: true });

console.log(stringify.toString());
```

webpack.config.js:
```
module.exports = {
	mode: "production",
	entry: "./index.js",
	target: "node",
	output: {
		filename: "packaged.js"
	}
};
```

package.json:
```
{
  "name": "jsonstringifytest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "fast-json-stringify": "^2.7.6"
  },
  "devDependencies": {
    "webpack": "^5.40.0",
    "webpack-cli": "^4.7.2"
  }
}
```

Then run:

```
npm i
npx webpack
node dist/packaged.js
```

### Expected Behavior

When running without debugmode, expected working serialization. Instead the packaged program crashes with `$asBoolean is not defined`.

For the debugmode example above, output contains:
```
function k(e){return e?"true":"false"}
/* ... */
json += $asBoolean(obj["valid"])
```

Notice how the function has been renamed, but the call to it has not. The result is that the generated code no longer compiles.

I expected output to contain either:

```
function $asBoolean (bool) {
  return bool && 'true' || 'false' // eslint-disable-line
}
/* ... */
json += $asBoolean(obj["valid"])
```

or possibly

```
function k(e){return e?"true":"false"}
/* ... */
json += k(obj["valid"])
```

**Comment by mcollina** [comment]
I would guess Webpack is minimizing your code and it shouldn't. Could you check how to disable that?

**Comment by diwic** [comment]
Indeed disabling minimization like below fixes the issue:

webpack.config.js
```
module.exports = {
	mode: "production",
	optimization: {
		minimize: false,
	},
	entry: "./index.js",
	target: "node",
	output: {
		filename: "packaged.js"
	}
};
```

...with the obvious drawback that minimization is now disabled.

Having had a look at the code, I believe the problem is the mix between functions and strings; i e, either let `$asBoolean` be a string in the first place:

```
const $asBoolean = `function $asBoolean (bool) { return bool && 'true' || 'false' }`;
```

or conistently use the value of `$asBoolean.name` instead of the string `'$asBoolean'` whenever code is added.

**Comment by jsumners** [comment]
I would close this as unsupported.

**Comment by zekth** [comment]
Can't you exclude `fast-json-stringify` using the minifier options? https://webpack.js.org/plugins/terser-webpack-plugin/#minify

**Comment by diwic** [comment]
> Can't you exclude `fast-json-stringify` using the minifier options? https://webpack.js.org/plugins/terser-webpack-plugin/#minify

Unfortunately, it seems like this is impossible, according to https://github.com/webpack-contrib/terser-webpack-plugin/issues/31

**Comment by mcollina** [comment]
> ...with the obvious drawback that minimization is now disabled.

I do not understand why this is a drawback for Node.js servers.

---

Anyhow, I'm happy to review a PR that fixes this. I can't guarantee it to be landed - it mostly depends if it reduces our benchmarks or if it makes our code more brittle.

**Comment by diwic** [comment]
> > ...with the obvious drawback that minimization is now disabled.
> 
> I do not understand why this is a drawback for Node.js servers.

The software runs on an embedded device. 
First, the embedded device might not have internet access, so we can't run "npm i" or something like that (that's why we need webpack in the first place). 
Second, the bandwidth to the embedded device might be slow (think 3G or 4G mobile link), so minimization matters.
Third, in case a competitor/hacker/etc gets his hands on a device we gain a little bit of security-by-obscurity by not exposing our source code in its original form. 

> Anyhow, I'm happy to review a PR that fixes this. I can't guarantee it to be landed - it mostly depends if it reduces our benchmarks or if it makes our code more brittle.

All right. The "make everything strings" version should be fairly simple to implement, I hope.
