### ISSUE TITLE
allOf withing $ref within allOf is ignored

### ISSUE THREAD

**Issue by LEVI-RIVKIN** [fastify/fast-json-stringify#368]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.24.0

### Node.js version

14.17.3

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

When trying to use an `allOf` within a `$ref` which is itself within an `allOf`, the inner `allOf` is simply ignored.

### Steps to Reproduce

```
const fastJson = require('fast-json-stringify');

const externalSchema = {
	nameSchema: {
		$id: 'nameSchema',
		type: 'object',
		properties: {
			name: {
				type: 'string'
			}
		}
	},
	user: {
		$id: 'user',
		type: 'object',
		allOf: [{
			$ref: 'nameSchema#'
		}, {
			properties: {
				id: {
					type: 'number'
				}
			}
		}]
	},
	fullUser: {
		$id: 'fullUser',
		type: 'object',
		allOf: [{
			$ref: 'user#'
		}, {
			properties: {
				age: {
					type: 'number'
				}
			}
		}]
	}
};

const user = { id: 1, age: 5, name: 'Test' };

// using the 'user' schema it's working as expected
const userStringify = fastJson({
	title: 'User Schema',
	$ref: 'user#'
}, { schema: externalSchema });
console.log('userStringify', userStringify(user));
// prints: `userStringify {"name":"Test","id":1}`

// using the 'fullUser' schema it ignores all the 'user' properties
const fullUserStringify = fastJson({
	title: 'Full User Schema',
	$ref: 'fullUser#'
}, { schema: externalSchema });
console.log('fullUserStringify', fullUserStringify(user));
// prints: `fullUserStringify {"age":5}`
```

I've traced the issue and it seems to be in the `buildCodeWithAllOfs` function. There, in case the inner `allOf` is immediate, it loops, otherwise it calls `buildCode`. The `buildCode` function then unpacks the `$ref` and handles it, but it doesn't take into account it could include another `allOf` inside.
Adding the following lines at the end of the `buildCode` function seems to solve it:
```
if (schema.allOf) {
	const builtCode = buildCodeWithAllOfs(location, code, laterCode, name);
	code += builtCode.code;
	laterCode += builtCode.laterCode;
}
```

### Expected Behavior

Should not ignore the inner `allOf`.

**Comment by mcollina** [comment]
Good finding! 
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
