### ISSUE TITLE
Support schema 2020-12

### ISSUE THREAD

**Issue by Eomm** [fastify/fast-json-stringify#386]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Support the JSON Schema 2020-12 draft standard:

- https://json-schema.org/draft/2020-12/release-notes.html 
- https://json-schema.org/specification-links.html#2020-12

I would try to list in this issue the TODOs to complete this task.

### Motivation

It should improve/simplify a lot the `fastify-swagger` stuff and it should be easier for users to create API documentation.

"they said": https://twitter.com/jsonschema/status/1488992487804911626?s=20&t=siJuq384dm4b4XhfDyJpWQ

**Comment by mcollina** [comment]
This is going to be a massive feature. What are the fundamental differences? I'm happy to loosely support all specs at the same time, i.e. just add the missing fields.
