### ISSUE TITLE
In som cases returns null which makes it difficult to locate the error. may should throw the error

### ISSUE THREAD

**Issue by aircloud** [fastify/fast-json-stringify#391]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

## Fastify version

3+

## Description

Recently, I'm using fast-json-stringify in some frameworks and projects (e.g. https://github.com/aircloud/fst-json: auto-generate JSON schema by typescript)

But I found a bad experience, such as the following code (this is cropped in my project code), which is an array, and each element may be an array or a number

```
exports.ETypeStringify = fastJson({
  "title": "EType",
  "type": "array",
  "items": {
    "anyOf": [
      {
        "type": "number"
      },
      {
         "type": "array",
        "items":  {
          "type": "object",
          "properties": {
            "attrA": {
              "type": "string"
            },
            "attrB": {
              "type": "number"
            },
            "attrX": {
              "type": "number"
            }
          },
          "required": [
            "attrA",
          ]
        }
      }
    ]
  }
});
console.log(this.ETypeStringify([3, [
  {
    attrA: "123",
    attrB: 10
  }, {
    attrA: "123",
    attrB: null
}]]))
```

the result：

```
[3,null]
```

At this time, the return of the second element is directly a null. In fact, only one attribute here is wrong. In actual business, it may have little impact, but returning a null directly will lead to more errors.

Also, when I have a little more object content and hierarchy, this kind of error that just returns a null is actually hard to locate.

In fact, when I encounter this kind of problem, I usually need to locate for a long time, and even use the dichotomy method.

I looked at the implementation of this repository and found that the validate of ajv returns false, but we don't have a good way to get and report this error.

I think it may be better to throw this error (users can do more things through try catch at this time), and at the same time, in order not to affect the existing logic, it can be solved by adding a new configuration field（for example， strict）.

Of course, because this change may be relatively large, I did not directly submit a Pull Request, but hoped to discuss it through an issue first. The change may be like this:

```
if ('anyOf' in schema) {
...
...
    if (options && options.strict) {
      code += `
        ${index === 0 ? 'let ajvErrors = [];' : ''}
      if (ajv.validate("${schemaKey}", ${testValue})) {
        ${nestedResult.code}
        continue;
      }
      ajvErrors = ajvErrors.concat(ajv.errors);
    `
    } else {
      code += `
        ${index === 0 ? 'if' : 'else if'}(ajv.validate("${schemaKey}", ${testValue}))
          ${nestedResult.code}
      `
    }
    laterCode = nestedResult.laterCode
  })
  if (options.strict) {
    code += `
      throw new Error("none match anyOf: " + formatAjvErrors(ajvErrors))
    `
  } else {
    code += `
      else json+= null
    `
  }
...
...
```

Of course, this code is definitely not perfect. It is best to sort out this error situation as a whole. I don't know what the main maintainers think about my predicament.

**Comment by mcollina** [comment]
The argument looks valid, I think we should throw in that case.

Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by aircloud** [comment]
> The argument looks valid, I think we should throw in that case.
> 
> Would you like to send a Pull Request to address this issue? Remember to add unit tests.

Let me think about how to do it better

Because the change here is likely to be a breaking change

For `anyof`,  if  throw an error directly, it is likely to cause problems in the previous user's code

For example, it is reasonable for the following code to return null:

```
exports.ETypeInterfaceStringify = fastJson({
  "title": "ETypeInterface",
  "type": "object",
  "properties": {
    "typeA": {
      "type": "string"
    },
    "typeB": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "number"
        }
      ]
    }
  },
  "required": [
    "typeA",
    "typeB"
  ]
});

console.log('ETypeInterfaceStringify:', this.ETypeInterfaceStringify({
  typeA: "a",
  typeB: NaN
}))
```

but it shares the same logic with the above example
