### ISSUE TITLE
Avoid leading and trailing {}

### ISSUE THREAD

**Issue by ronag** [fastify/fast-json-stringify#393]
I'm trying to optimise tracing to esc.

Currently I'm doing something like this:

```js
setInterval(() => {
  prefix = flatstr(
    `{ "create": { "_index": "ds" } }\n{ "@timestamp": "${new Date().toISOString()}", "worker": "${workerId}", "op": "`
  )
}, 1e3)
    
function trace(obj, op) {
  const doc = stringify(obj).slice(1, -1)
  traceData += prefix + `${op}", ${doc} }\n`
  if (traceData.length > 128 * 1024) {
    flushTraces()
  }
}
```

This works exceptionally well. However, I do have one unfortunate perf bottle neck. The. `slice(1, -1)` where I have to remove the leading and trailing {...}. I assume that fast-json-stringify causes V8 to flatten the string prior to this which is a bit unfortunate.

Is it possible or would it make sense to add an option to not include the leading/trailing { ... } in the output for these kind of use cases?

**Comment by zekth** [comment]
Is it possible yes, would it make sense? For most of the use cases no. But you're pointing an interesting topic.
Currently what's the structure of the object you're trying to stringify? Is there any specific reason for not having those trailing braces?
