### ISSUE TITLE
randomUUID is not a function

### ISSUE THREAD

**Issue by matthyk** [fastify/fast-json-stringify#397]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

PR #382 introduces the `randomUUID` function from the `crypto` package. The problem is that this function was only added with Node version 14.17. If you use FSJ now with an older node version you get the error `randomUUID is not a function`. Since FSJ has to support older Node versions due to Fastify, we can't use the randomUUID and have to replace it with some other UUID implementation.

**Comment by mcollina** [comment]
Which version of fastify are you using? Which version of fast-json-stringify are you using?

**Comment by matthyk** [comment]
I was working directly with fast-json-stringify (version 3.0.3). I tried to compile this schema:
```js
const schema = {
  type: 'object',
  properties: {
    obj: {
      oneOf: [
        {
          type: 'object',
          properties: {
            name: {
              type: 'string'
            }
          }
        },
        {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              name: {
                type: 'string'
              }
            }
          }
        }
      ]
    }
  }
}

```

When using Node version `>=14.17` no error occurs, but when using Node version `<14.17`, I get the error `randomUUID is not a function`.

**Comment by jsumners** [comment]
CI for this project is set to test on the latest LTS release lines. That means it is only supported on the latest version of 14.

**Comment by Eomm** [comment]
Adding an `$id` to the schema should workaround your issue:

https://github.com/fastify/fast-json-stringify/blob/2b055fad32d46fc12148be85248d89f75d28406c/index.js#L849
