### ISSUE TITLE
Possible serialization bug with null converted to empty string

### ISSUE THREAD

**Issue by Jnig** [fastify/fast-json-stringify#401]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.4

### Node.js version

14.19

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Arch

### Description

Hi, 

I'm using fastify with a response schema, which defines a property `name` of type `string`. When returning `null` an empty `string` is returned instead. I would've expected an error message.

Other values likes `objects`, `numbers`, `arrays` are also converted to a string. So it seems consistent. Perhaps it would be nice to have a strict mode, which returns an error message instead.

### Steps to Reproduce
```js
const fastify = require("fastify")({
  logger: true,
});

const opts = {
  schema: {
    response: {
      "2xx": {
        type: "object",
        properties: {
          name: {
            type: "string",
          },
        },
      },
    },
  },
};

// returns {"name": ""}
fastify.get("/", opts, function (request, reply) {
  reply.send({"name": null});
});

// returns {"name": "1,2,3"}
fastify.get("/array", opts, function (request, reply) {
  reply.send({"name": [1, 2, 3]});
});

// returns {"name": "1"}
fastify.get("/number", opts, function (request, reply) {
  reply.send({"name": 1});
});

// returns {"name": "[object Object]"}
fastify.get("/object", opts, function (request, reply) {
  reply.send({"name": {foo: "bar"}});
});

fastify.listen(3000, function (err, address) {
  if (err) {
    fastify.log.error(err);
    process.exit(1);
  }
});
```
### Expected Behavior

Instead of returning `{name: ""}` I would expect a error message like `name is not a string`.

**Comment by climba03003** [comment]
I think your assumption of this module is wrong. It is a serializer, not validator with serialize feature.
It should try it's best to match the requested schema.

**Comment by Jnig** [comment]
That makes sense - thanks for clarifying
