### ISSUE TITLE
Schema doesn't consider the `toJSON()` method

### ISSUE THREAD

**Issue by samchon** [fastify/fast-json-stringify#405]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.1.0

### Node.js version

16.6.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

Windows 11

### Description

If there's a class who've defined the `toJSON()` method and initialize a `Schema` following the return type of the `toJSON()` method, the `fast-json-stringify` be broken. It seems the `Schema` and `stringify()` function of the `fast-json-stringify` can't reflect the return value of the `toJSON()` method.

### Steps to Reproduce

If design a class who has a `toJSON()` method who returns a number type and create a `stringify` function with a `Schema` following the number type, the `stringify` function can't input the class type in the compilation level. If call the `stringify` function ignoring the compilation error by casting it as `any`, it always returns the `null` value.

```typescript
import faster from "fast-json-stringify";

class Operator
{
    public constructor
        (
            public readonly x: number, 
            public readonly y: number, 
            public readonly z: number
        )
    {
    }

    public toJSON(): number
    {
        return this.x + this.y + this.z;
    }
}

namespace OperatorModule
{
    export function toJSON(): number
    {
        return 2 + 3 + 4;
    }
}

class PropertyAssignment
{
    public readonly toJSON = () => 2 + 3 + 4;
}

const stringify = faster({ type: "number" });
console.log((stringify as any)(new Operator(2, 3, 4))); // null
console.log((stringify as any)(OperatorModule)); // null
console.log((stringify as any)({
    toJSON: () => 2 + 3 + 4
})); // null
console.log((stringify as any)(new PropertyAssignment())); // null
```

### Expected Behavior

Hope no compilation error with exact json string returns.

If you configure the parameter `doc` to capsule with this `Primitive`, the compilation error would be automatically fixed.

```typescript
/**
 * Build a stringify function using a schema of the documents that should be stringified
 * @param schema The schema used to stringify values
 * @param options The options to use (optional)
 */
declare function build(schema: build.AnySchema, options?: build.Options): (doc: any) => any;
declare function build(schema: build.StringSchema, options?: build.Options): (doc: Primitive<string>) => string;
declare function build(schema: build.IntegerSchema | build.NumberSchema, options?: build.Options): (doc: Primitive<number>) => string;
declare function build(schema: build.NullSchema, options?: build.Options): (doc: Primitive<null>) => "null";
declare function build(schema: build.BooleanSchema, options?: build.Options): (doc: Primitive<boolean>) => string;
declare function build(schema: build.ArraySchema | build.TupleSchema, options?: build.Options): (doc: Primitive<any[]>) => string;
declare function build(schema: build.ObjectSchema, options?: build.Options): (doc: object) => string;
declare function build(schema: build.Schema, options?: build.Options): (doc: Primitive<object | any[] | string | number | boolean | null>) => string;

type Primitive<Instance> = value_of<Instance> extends object
    ? Instance extends object
        ? Instance extends IJsonable<infer Raw>
            ? value_of<Raw> extends object
                ? Raw extends object
                    ? PrimitiveObject<Raw> // object would be primitified
                    : never // cannot be
                : value_of<Raw> // atomic value
            : PrimitiveObject<Instance> // object would be primitified
        : never // cannot be
    : value_of<Instance>;

type PrimitiveObject<Instance extends object> = Instance extends Array<infer T>
    ? Primitive<T>[]
    : 
    {
        [P in keyof Instance]: Instance[P] extends Function
            ? never
            : Primitive<Instance[P]>
    };

type value_of<Instance> = 
    is_value_of<Instance, Boolean> extends true ? boolean
    : is_value_of<Instance, Number> extends true ? number
    : is_value_of<Instance, String> extends true ? string
    : Instance;

type is_value_of<Instance, Object extends IValueOf<any>> = 
    Instance extends Object
        ? Object extends IValueOf<infer Primitive>
            ? Instance extends Primitive
                ? false
                : true // not Primitive, but Object
            : false // cannot be
        : false;

interface IValueOf<T>
{
    valueOf(): T;
}

interface IJsonable<T>
{
    toJSON(): T;
}
```

**Comment by Eomm** [comment]
I think this would be a good feature, it would fix the `Date` object too.

Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by samchon** [comment]
There's no problem when the JSON method returns another object type. The problem only occurs only when the returned type is not object like an atomic value type or array type. In nowadays, making an wrapper library [typescript-json](https://github.com/samchon/typescript-json) and considering purpose of the `fast-json-stringify`, I think this is not a bug, but just a spec.

When the compiled JSON string conversion function always check whether the target instance is an object and inspect whether it has a `toJSON()` method or not, its JSON conversion speed would be same like the native `JSON.stringify()` function. In such reason, I close this issue by my self.

I think that only one way to avoid this bug is to detecting, whether the instance comes from the `toJSON()` method or its own primitive value, on the TypeScript compilation level. Therefore, I've solved this problem by myself, enhacing my wrapper library [typescript-json](https://github.com/samchon/typescript-json) to just using the native `JSON.stringify()` function when the `Object.toJSON()` returns non-object type.

Of course, the solution is not enough within framework of the performance tuning. Thus, I'll improve the solution in the compilation level, let JSON string builder to call the `Object.toJSON()` method itself, without calling the native `JSON.stringify()` function.
