### ISSUE TITLE
`$ref` doesn't understand the `nullable` option

### ISSUE THREAD

**Issue by samchon** [fastify/fast-json-stringify#406]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.1.0

### Node.js version

16.6.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

Windows 11

### Description

To represent such hierarchical data, I've utilized the `$ref` and encountered the null exception.

If's possible to avoiding such null exception by defining duplicated external definition with nullable `false` and `true`, however, it seems too inefficient. I hope that the `$ref` to support the `nullable` option exactly. In the same reason, I hope the `anyOf` or `someOf` defined object to support the `nullable` option too.

```typescript
import faster from "fast-json-stringify";

// THE RECURSIVE STRUCTURE
interface IDepartment
{
    name: string;
    parent: IDepartment | null;
}

// CREATE STRINGIFY FUCTION
const stringify = faster({ $ref: "external/#o6" },
{
    external: {
        o6: {
            type: "object",
            properties: {
                name: {
                    type: "string",
                    nullable: false
                },
                parent: {
                    $ref: "external#/o6",
                    nullable: true
                }
            }
        }
    }
});

// TypeError: Cannot read property 'name' of null
stringify({
    name: "bottom",
    parent: {
        name: "middle",
        parent: {
            name: "top",
            parent: null
        }
    }
});
``````

### Steps to Reproduce

It's possible to reproduce the bug with such similar code.

```typescript
import faster from "fast-json-stringify";

// VERY SIMPLE STRUCTURE
interface IProduct
{
    name: string;
}

// CONSTRUCT STRINGIFY FUCTION
const stringify = faster
(
    {
        $ref: "external#/o4",
        nullable: true
    },
    {
        external: {
            o4: {
                type: "object",
                properties: {
                    name: {
                        type: "string",
                        nullable: false
                    }
                }
            }
        }
    }
);

// TypeError: Cannot read property 'name' of null
stringify(null);
```

### Expected Behavior

Hope upper codes to work without exception.

**Comment by climba03003** [comment]
Your example is not correct for using external schema.
There is no option called `external`.

If you need something that is `null`, you should not pass it in.
```js
const stringify = faster(
  { $ref: "external#/o6" },
  {
    schema: {
      external: {
        o6: {
          type: "object",
          properties: {
            name: {
              type: "string",
              nullable: false,
            },
            parent: {
              $ref: "external#/o6",
              nullable: true,
            },
          },
        },
      },
    },
  }
);

stringify({
  name: "bottom",
  parent: {
    name: "middle",
    parent: {
      name: "top",
      // if there is no parent, do not pass anything
    },
  },
});
```

**Comment by climba03003** [comment]
The problem seems to be not merging the schema with `$ref` schema. It is not limited to `nullable`, but all the properties that trying to override the `$ref` schema.

**Comment by samchon** [comment]
Thanks for fast response. I hope it to be fixed.

**Comment by climba03003** [comment]
We decided to follow the `JSON Schema 4-7` and do not allow the flexible usage described in `JSON Schema 2019-09`.
So, this current result is correct since the property is not allow to override.
You can check the detail start from https://github.com/fastify/fast-json-stringify/pull/408#issuecomment-1106078468

**Comment by samchon** [comment]
Got it. I've to define the duplicated object type for each nullable and not nullable case.

I should keep below code for forever.

https://github.com/samchon/typescript-json/blob/abf3866d32b0aa86e2de471d62e681ca57fc8813/src/factories/MetadataFactory.ts#L166-L178
