### ISSUE TITLE
Made a wrapper library who needs `only one line`

### ISSUE THREAD

**Issue by samchon** [fastify/fast-json-stringify#407]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I love performance tuning and also love this `fast-json-stringify` library in the same reason. I really appreciate you that supporting such beautiful and powerful library as open source. I have even tried to evangelized this wonderful library, however many people around me have said:

> Building schema is too hard and annoying. When using TypeScript, it's hard to manage heterogeneous type definitions, TypeScript type and `fast-json-stringify` schema. If some TypeScript type be refactored freequently, how to reflect those refactorings into the `fast-json-stringify` schema.

In such reason, I've made a wrapper library of this `fast-json-stringify` with only one line. The new wrapper library is the [typescript-json](https://github.com/samchon/typescript-json) and it constructs the `fast-json-stringify` automatically by analyzing the TypeScript type, byt itself like below. I think such convenient method have supported, much more TypeScript programmers may install and love this `fast-json-stringify` library.

```typescript
import TSON from "typescript-json";

TSON.stringify<T>(input);
const stringify = TSON.createStringifier<T>();
stringify(input);
```

**Comment by mcollina** [comment]
Amazing work! I didn't know TS could do that. How can we help?

**Comment by samchon** [comment]
The implementation has been already finished and I will just follow this library's update. Thanks for providing this wonderful library.

**Comment by samchon** [comment]
I need to optimize my library whether to use any type or exact json schema considering the generic argument. However, which type is effect, it has already been posted on your README article. Really thanks.
