### ISSUE TITLE
Ignore invalid number value

### ISSUE THREAD

**Issue by ivan-tymoshenko** [fastify/fast-json-stringify#431]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Now, if number/integer value is invalid, it will be skipped. Is that expected behavior?

```js
const stringify1 = fastJson({ type: 'object', properties: { a: { type: 'number' }} })
const stringify2 = fastJson({ type: 'object', properties: { a: { type: 'number', nullable: true }} })

stringify1({ a: 'invalid' }) // {}
stringify2({ a: 'invalid' }) // {}
```

**Comment by jsumners** [comment]
If I recall, it _is_ expected. There's no way to represent `undefined` in JSON and using any other value to indicate failure is ambiguous at best.

**Comment by RafaelGSS** [comment]
I think it should be compliant with other types. In that case, returning `null`.

**Comment by ivan-tymoshenko** [comment]
What about throwing an error if someone sent something that we can't convert to the number?

**Comment by jsumners** [comment]
> What about throwing an error if someone sent something that we can't convert to the number?

I cannot recall the decision made previously. If that is what other invalid values do, then this one should do the same.

**Comment by ivan-tymoshenko** [comment]
@jsumners I think there was taken a few different decision for different cases. It's better to think about it again considering all cases.

The general question is what should we do if we can't convert input type to schema type. This applies not only to numbers, but now we are talking only about them.

There is at least three different ways to deal with it, I found in the code.

```js
const stringify1 = fastJson({
  type: 'object',
  properties: { a: { type: 'number' }}
})

const stringify2 = fastJson({
  type: 'array',
  items: { type: 'number' }
})

const stringify3 = fastJson({
  type: 'array',
  items: [{ type: 'number' }]
})

stringify1({ a: 'string' }) // {}
stringify2(['string']) // [null]
stringify3(['string']) // throw new Error(`Item at ${i} does not match schema definition.`)
```

1) Ignoring incorrect value if it's an object property. It has obvious drawback. The object without the value and object with incorrect value will look the same after serialization. And it can't be the general solution, because we can't skip values in the array or if it's a top level value.

2) Replacing incorrect value with null. It seems to me better than ignoring value, but there are also drawbacks I can see. First, you can't differ object with null value and object with incorrect value. Second, it's required properties. If it's incorect required property we throw an error "property is required" (which is also, IMHO, not really correct, because property is exist, but it has different type; but let's talk about it later). So if it's required property we will throw an error, if it's optional we will return null. It's not really clear.

3) Throwing an error will remove indeterminacy. If the input was serialized, it means that all passed values were matched their types or were converted to them. null value would be possible only if you passed null value. 

I'd rather to get an error if the data type I specified in the schema not only doesn't match, but can't be cast, than get a null value or no value at all. But it's only my personal opinion.

**Comment by mcollina** [comment]
I think having a consistent behavior is important. I'm ok for throwing.

I don't want this to become a validator - as the same time I can see we need to be consistent.
