### ISSUE TITLE
Loose Object property checking support

### ISSUE THREAD

**Issue by benderTheCrime** [fastify/fast-json-stringify#45]
Co-related to my issue raised here:
https://github.com/fastify/fast-json-stringify/issues/44

I have a use case to just have a loose object inside of a well-defined schema.

I suppose this issue would satisfy this use case as well: 
https://github.com/fastify/fast-json-stringify/issues/29

because then I could just specify the Object had a pattern property of ".*" with types `['string', 'number', 'null', 'boolean', 'object', 'array']` and then refs in the properties and items. This may even be better (read: more feasible) than loose Objects because it still forces you to be declarative about the types of the expected properties in the Object.

However, this still seems like abusive use of the multiple typing. Unfortunately, as much as I'd like to say that it was always possible to predict the types of properties in all of the Objects I'm attempting to stringify, there's always going to be a use case for Objects containing loosely-defined payloads.

Any thoughts on this as a feature? Or thoughts on solving it with the multi-typing functionality issue?

**Comment by mcollina** [comment]
My only problem with multiple typing is that if we could implement it in a way that is *fast*. There might be a point of diminishing return with this approach, and I would not like to trade features for throughput.

**Comment by benderTheCrime** [comment]
In terms of "loose checking" specifically, I think "additionalProperties" covers the use case by just letting JSON.stringify deal with it if you can't explicitly declare the type.
