### ISSUE TITLE
breaking `fastify` standalone error serializer build

### ISSUE THREAD

**Issue by climba03003** [fastify/fast-json-stringify#459]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

3.0.1

### Stopped working in version

4.0.0

### Node.js version

*

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

*

### 💥 Regression Report

I think it related to the refactor of https://github.com/fastify/fast-json-stringify/pull/423

Debug mode no longer work like `README.md` describe.

https://github.com/fastify/fastify/issues/3995

### Steps to Reproduce

```
const debugCompiled = fastJson({
  title: 'default string',
  type: 'object',
  properties: {
    firstName: {
      type: 'string'
    }
  }
}, { debugMode: true })

console.log(debugCompiled) // it is an array of functions that can create your `stringify` function
console.log(debugCompiled.toString()) // print a "ready to read" string function, you can save it to a file

const rawString = debugCompiled.toString()
const stringify = fastJson.restore(rawString) // use the generated string to get back the `stringify` function
console.log(stringify({ firstName: 'Foo', surname: 'bar' })) // '{"firstName":"Foo"}'
```

**Comment by climba03003** [comment]
I recommend we provide a function for `standalone` mode.

**Comment by ivan-tymoshenko** [comment]
I'm sorry. There is a lack of tests here, so it's easy to break something. I will take a look at this.

**Comment by ivan-tymoshenko** [comment]
@climba03003 I took a quick look at this problem. #423 didn't break it. The restore function compiles stringify function from debugCompiled but never from debugCompiled.toString().

https://github.com/fastify/fast-json-stringify/blob/b57abf1e927c5906c70f8c0d9cb140def4332f9b/test/debug-mode.test.js#L47

**Comment by climba03003** [comment]
> @climba03003 I took a quick look at this problem. #423 didn't break it. The restore function compiles stringify function from debugCompiled but never from debugCompiled.toString().
> 
> https://github.com/fastify/fast-json-stringify/blob/b57abf1e927c5906c70f8c0d9cb140def4332f9b/test/debug-mode.test.js#L47

It breaks because of multiple of PR.
`fastify` build script is actually building a standalone code which the `debug` mode should do.

`Serializer` is never exported, so no matter how I modify and match the current implementation of `debug` mode.
It will never be success.

**Comment by climba03003** [comment]
Nevermind, I created a PR for the `fastify` use-case.
https://github.com/fastify/fast-json-stringify/pull/460
