### ISSUE TITLE
BigInt Problem

### ISSUE THREAD

**Issue by conioX** [fastify/fast-json-stringify#465]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.0

### Plugin version

4.2.0

### Node.js version

14.00

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

Windows 11

### Description

Hi Guys 

I found a problem when use fastify with prisma.

when my prisma schema return BigInt fastify return this error 

`{"statusCode":500,"error":"Internal Server Error","message":"Do not know how to serialize a BigInt"}`

when i search inside prisma issue i found this issue 

https://github.com/prisma/studio/issues/614

this issue not come from prisma but the problem come from JSON.stringify, i think fast-json-stringify need to handle this

### Steps to Reproduce

1. install fastify-cli
2. install prisma
3. create db with bigint schema

**Comment by jsumners** [comment]
BigInt does not support serialization to JSON.

**Comment by climba03003** [comment]
We should handle `BigInt` according to the `README.md`.

https://github.com/fastify/fast-json-stringify/blob/12fa1e90a27a27abfcce5be3adac55de208795d3/README.md?plain=1#L148-L152
