### ISSUE TITLE
Release plan for the Ajv reference fix

### ISSUE THREAD

**Issue by mcollina** [fastify/fast-json-stringify#468]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Here is my proposal for the release of https://github.com/fastify/fast-json-stringify/pull/462:

1) ship fast-json-stringify v5 with the above change as a precaution.
2) release fast-json-stringify-compiler with https://github.com/fastify/fast-json-stringify-compiler/pull/14 and the fjs v5 bump; this will me a semver-major release release for fast-json-stringify-compiler.
3) send a PR to fastify to update all the above in a minor release
4) close https://github.com/fastify/fast-json-stringify/pull/464 as won't fix.

Did I understood all the fixes correctly? Is this a feasible plan?

cc @delvedor @jsumners @Eomm @climba03003 @ivan-tymoshenko

**Comment by Eomm** [comment]
> Did I understood all the fixes correctly? Is this a feasible plan?

Yes, it is.

Just to be sure: will the `fast-json-stringify-compiler` release a major as well?

**Comment by mcollina** [comment]
> > Did I understood all the fixes correctly? Is this a feasible plan?
> 
> Yes, it is.
> 
> Just to be sure: will the `fast-json-stringify-compiler` release a major as well?

Yes

**Comment by climba03003** [comment]
Good to me. It is easy to revert in `fastify` when it has large impact.

**Comment by jsumners** [comment]
Go for it.

**Comment by ivan-tymoshenko** [comment]
PR at Fastify, where it all comes together. Now via git-dependency. https://github.com/fastify/fastify/pull/4049
