### ISSUE TITLE
`Infinity` and `-Infinity` value must be `null`

### ISSUE THREAD

**Issue by samchon** [fastify/fast-json-stringify#474]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.0.0

### Node.js version

18.4.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

https://github.com/fastify/fast-json-stringify/issues/221

Long time ago, `fast-json-stringify` had fixed the `Inifinity` bug.

But nowadays, it seems being revived.

### Steps to Reproduce

When define below structure and assign `Infinity` value, it does not be `null` but `Infinity`.

```typescript
export interface IBox3D {
    scale: IPoint3D;
    position: IPoint3D;
    rotate: IPoint3D;
    pivot: IPoint3D;
}
export interface IPoint3D {
    x: number;
    y: number;
    z: number;
}
```

```json
{"scale":{"x":Infinity,"y":-Infinity,"z":39},"position":{"x":38,"y":65,"z":93},"rotate":{"x":17,"y":65,"z":84},"pivot":{"x":73,"y":64,"z":69}}
```

### Expected Behavior

Be `null`.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by samchon** [comment]
Looking at the $asNumber function, it is throwing error when NaN comes.

In the same reason, may I throw an exception when infinite value comes?

**Comment by mcollina** [comment]
go for it!

**Comment by samchon** [comment]
Oops, already be done. Great.
