### ISSUE TITLE
Worse performance with response schema when 'const' keyword is used

### ISSUE THREAD

**Issue by DanieleFedeli** [fastify/fast-json-stringify#502]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.3.0

### Node.js version

16.13.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.0

### Description

When specifying the response schema with 'const' I noticed that the RPS decreased. 

### Steps to Reproduce

Options used: 
```
{
  schema: {
    response: {
        200: {
          type: "object",
          properties: {
            msg: { type: "string" },
          }
      }
   }
}
```
Schema benchmark: 		
<img width="718" alt="Screenshot 2022-08-07 alle 12 06 23" src="https://user-images.githubusercontent.com/37077048/183285845-a2fd096e-b03f-411a-87b8-b729f961de5d.png">

Options used: 
```
{
  schema: {
    response: {
        200: {
          type: "object",
          properties: {
            msg: { const: "hello world" },
          }
      }
   }
}
```
Schema with const:
<img width="675" alt="Screenshot 2022-08-07 alle 12 08 13" src="https://user-images.githubusercontent.com/37077048/183285902-c532e8ed-07a7-49f8-ac9a-72e81ff78b83.png">

Repository with the code: https://github.com/DanieleFedeli/fastify-response-schema-issue

### Expected Behavior

I expect at least the same performance when specifying const in the schema.

**Comment by Uzlopak** [comment]
How is the performance if we also use type: "string" or if we use enum instead of const?

**Comment by DanieleFedeli** [comment]
With type string

```javascript
{
  type: "object",
  properties: {
    msg: { type: "string", const: "hello world" },
  }
}
```
<img width="765" alt="Screenshot 2022-08-07 alle 16 18 25" src="https://user-images.githubusercontent.com/37077048/183295181-9b4c6a90-9e1f-4e37-9f50-e461bc3aeed6.png">

With enum

``` javascript
{
  type: "object",
  properties: {
    msg: { enum: ["hello world"] },
  }
}
```
<img width="741" alt="Screenshot 2022-08-07 alle 16 20 00" src="https://user-images.githubusercontent.com/37077048/183295248-813cde28-b707-45ee-b029-089ca21a7399.png">


It improves drastically

**Comment by climba03003** [comment]
I would say it is expected. 
When the `type` is not defined and `const` is exist, `FJS` need to guess whether the content is meet is schema or not.
So, it went through `ajv` for the guessing and it is expected to be slow in this case.

https://github.com/fastify/fast-json-stringify/blob/d14112bc2f35771e42404a0f419d51adacf3bea0/index.js#L869-L874

**Comment by Uzlopak** [comment]
But i can determine the type of const before i use it in ajv. So do we have to improve the docs or should we write a function which traverses the entries for const and determines the corresponding type?

**Comment by RafaelGSS** [comment]
+1 to mention it in the docs and open a new fresh issue to optimize it as we can.
