### ISSUE TITLE
LGTM-Alert Prototype pollution?

### ISSUE THREAD

**Issue by Uzlopak** [fastify/fast-json-stringify#517]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

We should just check if this is a valid alert or not.

https://lgtm.com/projects/g/fastify/fast-json-stringify?mode=tree&ruleFocus=1513136283260

According to lgtm it was introduced with #504

**Comment by mcollina** [comment]
It's not a problem: https://github.com/fastify/fast-json-stringify#security

**Comment by climba03003** [comment]
Even the alert itself should be false positive.

`fjsCloned` is a symbol, not user provided string. It can never be `__proto__` and trigger the problem described.
