### ISSUE TITLE
Support for MongoDB ObjectId type

### ISSUE THREAD

**Issue by marek-benes** [fastify/fast-json-stringify#566]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Hello,

Mongo database is used very often with Fastify. However, native objectID type represents the primary key is not supported in the parse function. Could you add support for this type, please?

**Comment by jsumners** [comment]
Define your own object that supports the `toJSON` method that provides the serialization.
