### ISSUE TITLE
(docs) document `simultaneously `

### ISSUE THREAD

**Issue by gfortaine** [fastify/fast-json-stringify#578]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

It seems that [`simultaneously`](https://github.com/fastify/fast-json-stringify/pull/263) is missing from the README. However, it seems particularly useful in some cases ([multiple types](https://github.com/fastify/fast-json-stringify/issues/193), [deep object types](https://github.com/fastify/fast-json-stringify/issues/412)) cc @eeom

**Comment by climba03003** [comment]
When you look at the test, `simultaneously` is not a keyword in `JSON Schema`.
It just the name of property. So, there is no function called `simultaneously` but a feature to accept multiple types e.g. `type: ['string', 'object']`
