### ISSUE TITLE
Root references require the hash

### ISSUE THREAD

**Issue by dougrich** [fastify/fast-json-stringify#60]
Gist with the issue [here](https://gist.github.com/dougrich/f5dc109a6695436684e47c25f3bf6fa0)

_Node Version_: v8.0.0
_fast-json-stringify-version_: 0.15.1
_OS_: Windows 10, 64bit

References that do not have a hash cause an exception.

Good:
```js
const goodSchema = {
  title: 'Example Schema',
  type: 'object',
  properties: {
    nickname: {
      $ref: 'strings#'
    }
  }
}
```

Bad:
```js
const badSchema = {
  title: 'Example Schema',
  type: 'object',
  properties: {
    nickname: {
      $ref: 'strings' // <-------- note the missing hash
    }
  }
}
```

Exception that is thrown looks like this:
```
...\node_modules\fast-json-stringify\index.js:354
  var walk = ref[1].split('/')
                   ^
TypeError: Cannot read property 'split' of undefined
```

As far as I can tell, not having the hash is valid. [example1](https://spacetelescope.github.io/understanding-json-schema/structuring.html#the-id-property), [example2](https://cswr.github.io/JsonSchema/spec/definitions_references/#formal-specification_2)

It looks like [here](https://github.com/fastify/fast-json-stringify/blob/master/index.js#L354) it should handle the case where there is no hash present - it could skip the walk.

Thoughts?

Thank you for your work with this library, it's incredibly useful. 😄

**Comment by mcollina** [comment]
Good catch! Would you like to send a PR?

**Comment by dougrich** [comment]
Yes, thanks!

I've sent out the PR - let me know if there's any changes you'd like to be made or additional steps beyond running tests.
