### ISSUE TITLE
missing options in types

### ISSUE THREAD

**Issue by albanm** [fastify/fast-json-stringify#602]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.5.0

### Node.js version

18

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

whatever

### Description

The documentation references option largeArrayMechanism and largeArraySize but they are missing from the Option type in types/index.d.ts and therefore cannot be used from typescript code.

### Steps to Reproduce

in typescript:

import fastJsonStringify from 'fast-json-stringify';
fastJsonStringify(responseSchema, { largeArrayMechanism: 'json-stringify', largeArraySize: 1000 });

**Comment by Uzlopak** [comment]
They exist?!

https://github.com/fastify/fast-json-stringify/blob/d8e22cde37412415473edfd26974788082db085e/types/index.d.ts#L182

**Comment by albanm** [comment]
Well that is weird I just made an npm install and they are not here.

```sh
$ cat node_modules/fast-json-stringify/package.json | grep version
  "version": "5.5.0",
$ cat node_modules/fast-json-stringify/types/index.d.ts | grep largeArraySize
$ 

```

**Comment by albanm** [comment]
See also https://cdn.jsdelivr.net/npm/fast-json-stringify@5.5.0/types/index.d.ts

**Comment by Uzlopak** [comment]
@mcollina 
We need a release.:)

**Comment by mcollina** [comment]
Done
