### ISSUE TITLE
Broken error message for missing required property

### ISSUE THREAD

**Issue by mcollina** [fastify/fast-json-stringify#604]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

v5.5.0

### Stopped working in version

v5.6.0

### Node.js version

18.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

ventura

### 💥 Regression Report

The error message is now reporting "NaN" instead of the property name for the latest fast-json-stringify release.

### Steps to Reproduce

Run the following in this repo:

```
'use strict'

const assert = require('assert')
const fjs = require('./index')
const schema = {
  type: 'object',
  properties: {
    fullName: { type: 'string' },
    phone: { type: 'number' }
  }
}

const input = {
  fullName: 'Jone',
  phone: 'phone'
}

const render = fjs(schema)

try {
  render(input)
} catch (err) {
  assert.equal(err.message, 'The value "phone" cannot be converted to a number.')
}
```

### Expected Behavior

The correct property name is listed in the error message

**Comment by mcollina** [comment]
@Uzlopak I think this is one of your fixes

**Comment by ivan-tymoshenko** [comment]
@mcollina  I think it's the same problem:
https://github.com/fastify/fast-json-stringify/issues/603#issuecomment-1439886724

**Comment by mcollina** [comment]
See the above example, this is a fjs problem.

**Comment by mcollina** [comment]
This was caused by https://github.com/fastify/fast-json-stringify/commit/07a9bcc72e0996e4a412ab74ac0e4009bd7e9640

**Comment by mcollina** [comment]
Seems a different bug than #603

**Comment by ivan-tymoshenko** [comment]
Yeah, sorry. I was confused with the issue title. Very similar.
