### ISSUE TITLE
standalone mode can't be devDependancy

### ISSUE THREAD

**Issue by Eomm** [fastify/fast-json-stringify#624]
The last fastify release https://github.com/fastify/fastify/compare/4.16.0...4.16.3 shows how the standalone mode now requires fjs as a dependency instead of a dev-dependancy because of this requirement:

```js
  const { dependencies } = require('fast-json-stringify/lib/standalone')
```
https://github.com/fastify/fastify/blob/b3ebbdc1ab363233b7728d2bcb4a5b8fe64ccfb3/lib/error-serializer.js#L5

I think the standalone mode was designed to produce a js file that can run without fjs

ref: https://github.com/fastify/fast-json-stringify/pull/617

**Comment by mcollina** [comment]
cc @ivan-tymoshenko

**Comment by Eomm** [comment]
No, it is not - the readme is updated tho

I wonder if we have other options to make it fully standalone

**Comment by ivan-tymoshenko** [comment]
If the standalone code needs Ajv for validation - then no.
If the standalone code doesn't need Ajv for validation - yes, by printing half of the library to the standalone file.

This way of dealing with it is more flexible. We can use any library in the runtime.
Example: https://github.com/fastify/fast-json-stringify/issues/612

**Comment by Eomm** [comment]
Yeah - there is no clue on this
