### ISSUE TITLE
`node:crypto` issues in Next.js

### ISSUE THREAD

**Issue by inlet** [fastify/fast-json-stringify#659]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.9.0

### Node.js version

20.6.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Sonoma 14.0

### Description

When using `fast-json-stringify` in a Next.js site (client component), it breaks because it refers to `node:crypto`.

It outputs:

```
Module build failed: UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:crypto
./node_modules/fast-json-stringify/index.js
```

### Steps to Reproduce

See this [codesandbox demo](https://codesandbox.io/p/sandbox/fast-json-stringify-gmgfyv?file=%2Fapp%2FApp.tsx%3A19%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cloiew4o900073b6glu7gbp0c%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cloiew4o900033b6gnbfhf41z%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cloiew4o900053b6ggjd5j2b9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cloiew4o900063b6gab9smq93%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cloiew4o900033b6gnbfhf41z%2522%253A%257B%2522id%2522%253A%2522cloiew4o900033b6gnbfhf41z%2522%252C%2522activeTabId%2522%253A%2522cloieypsv00nz3b6ghykrp8ys%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cloiew4o800023b6ggzl4hmd8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%252C%2522id%2522%253A%2522cloieyb4x00ig3b6g9eedyhye%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252FApp.tsx%2522%252C%2522id%2522%253A%2522cloieypsv00nz3b6ghykrp8ys%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522cloif0v4g019c3b6gk4r5qm0a%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Flayout.tsx%2522%252C%2522id%2522%253A%2522cloif2ka501sf3b6gtg3nnkvg%2522%252C%2522mode%2522%253A%2522temporary%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522cloiew4o900063b6gab9smq93%2522%253A%257B%2522id%2522%253A%2522cloiew4o900063b6gab9smq93%2522%252C%2522activeTabId%2522%253A%2522cloif2xdv01vm3b6g589coduf%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522cloiewh7t00az3b6gcdt1z73p%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522cloif2xdv01vm3b6g589coduf%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cloiew4o900053b6ggjd5j2b9%2522%253A%257B%2522id%2522%253A%2522cloiew4o900053b6ggjd5j2b9%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cloiew4o900043b6gidaoowso%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cloiew4rc0003dxjeg675fca1%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cloiewemh008v3b6gjhp2bjdy%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cloiewemh008v3b6gjhp2bjdy%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Expected Behavior

It should work in the browser as well. When running this it should not prompt this error but instead continue compiling and rendering the result in the browser

**Comment by inlet** [comment]
FYI Version `5.8.0` dit work in the browser using Next app

**Comment by mcollina** [comment]
@Fdawgs guess that `node:` change actually broke somebody.

**Comment by mcollina** [comment]
cc @Ethan-Arrowood wdyt?

**Comment by Ethan-Arrowood** [comment]
Interesting. There must be some kind of polyfill? happening that gets broken by the `node:` prefix. I'll crosspost to the Next.js crew and let them investigate further.

**Comment by Ethan-Arrowood** [comment]
Okay as I expected, Next.js does polyfill `crypto`, but they say this is not great and that using `fast-json-stringify` in a client component is wrong (since you shouldn't be using Node.js deps in a client component). When `node:` was added, Next.js started failing (as expected). They've kept in their polyfill as to not break a ton of existing projects, but have started hard failing when they notice `node:` in imports. @mcollina I think you are okay to add them back in if this module is truly Node.js only (which I do believe it is).

**Comment by inlet** [comment]
I agree with @Ethan-Arrowood here, if `fast-json-stringify` is ment for node only then it’s good practice to bring back the `node:` prefixes in

**Comment by Uzlopak** [comment]
Proposed #661
