### ISSUE TITLE
Tuple of date-time does not allow Date

### ISSUE THREAD

**Issue by qwelias** [fastify/fast-json-stringify#662]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

latest

### Node.js version

20

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Arch

### Description

Throws on stringifying `Date` for schema with `{type: 'string',format: 'date-time'}`

### Steps to Reproduce

```js
require('./index.js')({
  title: 'dates tuple',
  type: 'object',
  properties: {
    dates: {
      type: 'array',
      minItems: 2,
      maxItems: 2,
      items: [
        {
          type: 'string',
          format: 'date-time'
        },
        {
          type: 'string',
          format: 'date-time'
        }
      ]
    }
  }
})({
  dates: [new Date(1), new Date(2)]
}) // Error: Item at 0 does not match schema definition.
```

### Expected Behavior

Does not throw on stringifying `Date` for schema with `{type: 'string',format: 'date-time'}`

**Comment by qwelias** [comment]
@mcollina hi, I'm willing to contribute here, just need a bit if advice regarding my previous comment when you have time

**Comment by ivan-tymoshenko** [comment]
@qwelias Yes, the logic should be simmilar to the `buildMultiTypeSerializer`. 
https://github.com/fastify/fast-json-stringify/blob/4f6f7b809fc7148a40e8f07cc81a658757e81b68/index.js#L737

P.S. IMO this check is redundant, but dropping it would be a breaking change, so we should support this.
https://github.com/fastify/fast-json-stringify/pull/524
