### ISSUE TITLE
Remove dynamic requirements

### ISSUE THREAD

**Issue by scriptjs** [fastify/fast-json-stringify#67]
I use webpack on the server side. ES 6 expects static imports. As a result 'long' and 'uglify-es' emit the following warnings. In general, I believe it is bad practice to include dynamic requirements in a module - even while a dynamic import is being considered in ES.

Let's think of a better way to handle adding these capabilities. I have replaced my project path with '/path/to/project' in the traces below:

```
WARNING in ./node_modules/fast-json-stringify/index.js
Module not found: Error: Can't resolve 'long' in '/path/to/project/node_modules/fast-json-stringify'
 @ ./node_modules/fast-json-stringify/index.js 9:11-26
 @ ./node_modules/fastify/lib/reply.js
 @ ./node_modules/fastify/fastify.js
 @ ./es6/lib/app/index.js
 @ ./es6/index.js

WARNING in ./node_modules/fast-json-stringify/index.js
Module not found: Error: Can't resolve 'uglify-es' in '/path/to/project/node_modules/fast-json-stringify'
 @ ./node_modules/fast-json-stringify/index.js 608:13-33
 @ ./node_modules/fastify/lib/reply.js
 @ ./node_modules/fastify/fastify.js
 @ ./es6/lib/app/index.js
 @ ./es6/index.js

WARNING in ./node_modules/fast-json-stringify/index.js
Module not found: Error: Can't resolve 'uglify-es/package.json' in '/path/to/project/node_modules/fast-json-stringify'
 @ ./node_modules/fast-json-stringify/index.js 609:24-57
 @ ./node_modules/fastify/lib/reply.js
 @ ./node_modules/fastify/fastify.js
 @ ./es6/lib/app/index.js
 @ ./es6/index.js
```

**Comment by mcollina** [comment]
I don’t know how I can help. We are not adding those as direct dependencies, as they are not needed for this module to function. They are, as stated in the readme, optional.

This module is not ES, it’s commonjs and what we are doing is perfectly ok.

You should configure webpack to leave this as it is. Please send a PR if we need to add some config in package.json to tell webpack to leave this alone.

If you want to use ESM in Node, I would recommend to use https://github.com/standard-things/esm instead.

**Comment by scriptjs** [comment]
@mcollina My suggestion is let's not include them if they are not needed for the module to function and look at an alternate method for adding these capabilities.

I think its important to show some sensitivity to ES, we are all headed in this direction. Resolving these sort of issues ultimately reduces unnecessary code. Let me try something here and we can talk about it with a PR. I really don't want to fork fastify projects and would rather contribute if possible.

**Comment by jsumners** [comment]
The solution is to not needlessly transpile code.

**Comment by scriptjs** [comment]
@jsumners Hello, I did not suggest that. I think a possible solution is providing options is a better solution to dynamically requiring modules. Let's just make it work for everyone.

**Comment by scriptjs** [comment]
@mcollina , @jsumners 
I determined a solution for webpack without modifications only because these are both optional dependencies. This can be resolved with the following in the webpack config.
```
  externals: [
    'long', // optional dependency fast-json-stringify
    'uglify-es', // optional dependency fast-json-stringify
    'uglify-es/package.json' // optional dependency fast-json-stringify
  ]
```
I think this should be identified for other in the README since the critical warning will appear for anyone bundling a Fastify server. Webpack is not so much about transpiling as bundling. Speed is much better when you serve from a single file. We're getting to a point where with node 10 we'll be using the ES module system regardless. From node 8.5.0, it can be used with a flag without any transpilation.

**Comment by jsumners** [comment]
I'd have to see some numbers before I believe that all code in a single file has any impact whatsoever on a long running process.

**Comment by scriptjs** [comment]
@jsumners I am trying to be helpful and participate in the evolution of fastify. Can we do the PR for the README.md or not? I have no desire to get into bikeshedding about transpilation. I've determined a solution that may be helpful to others. Its only a matter or whether this gets documented.

**Comment by jsumners** [comment]
Submit the PR. I will stay out of it.

**Comment by mcollina** [comment]
Send the PR to the readme.

@scriptjs that warning is caused by Webpack, not by ESM. The code in this module should behave just fine with native ESM. Webpack is not native ESM, and it does not behave like native ESM, it just have the same syntax of ESM.

**Comment by scriptjs** [comment]
I will do this. Yes, I understand the warning and the current situation. A dynamic import has been proposed https://github.com/tc39/proposal-dynamic-import. Node.js is also sorting this out for Node 10 so there is a better picture for modules as the bundling and packaging of server side code continues to evolve.
