### ISSUE TITLE
merged schema cache is messed up

### ISSUE THREAD

**Issue by climba03003** [fastify/fast-json-stringify#676]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.x

### Plugin version

5.11.0

### Node.js version

20.x

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

I suspect it is deal to the merged schema cache is not properly handled, which means two seperate build procedure may try to use the same cache but it never exists.

### Steps to Reproduce

```js
import { build } from 'fast-json-stringify'

const schema = {
  type: 'object',
  properties: {
    enums: {
      type: 'string',
      anyOf: [
        { type: 'string', const: 'FOO' },
        { type: 'string', const: 'BAR' },
        { type: 'string', const: 'BAZ' },
      ]
    }
  }
}

build(schema, {
  schema: {}
})

build(schema, {
  schema: {}
})
```

**Comment by climba03003** [comment]
cc @ivan-tymoshenko

**Comment by ivan-tymoshenko** [comment]
@climba03003 yeap the problem is with attaching a symbol property to the schema. I will fix it soon. The release is reverted.
