### ISSUE TITLE
Date coercion isn't supported by TypeScript types

### ISSUE THREAD

**Issue by tmcw** [fastify/fast-json-stringify#682]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.26.0

### Node.js version

20.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.3

### Description

The readme has the following code example:

```ts
const stringify = fastJson({
  title: 'Example Schema with string date-time field',
  type: 'string',
  format: 'date-time'
})

const date = new Date()
console.log(stringify(date)) // '"YYYY-MM-DDTHH:mm:ss.sssZ"'
```

This is great and desired behavior. But it doesn't typecheck. Here's a [TypeScript playground link for the message](https://www.typescriptlang.org/play?ssl=10&ssc=1&pln=10&pc=30#code/JYWwDg9gTgLgBAMwIYGcYCkUQHaKhEOAImTQFoArLbMtKYbAc2AQE8iBuAKC4GMc0cOg2Zs4AXkSoM1ABQBvLnDgxgMADYBTAFzEAogA8k4LXADKvABaaQSOAHc1loTHpM4AEyQxNZVSE1EYE11DyIAGiUVVjAdYmEmCKiEaFsYXSIvHz9QTSSAXwBKbj4BeCzAyWxNezgAEW9NWWLS7CwtADp1CEZZBNFWWQrC4qA)

Which is:

> Argument of type 'Date' is not assignable to parameter of type 'string'.

### Steps to Reproduce

Add a string type with format: `date-time` as the spec for fast-json-stringify

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests. We use tsd for types.

**Comment by tmcw** [comment]
Yep! Working on one now, a little confused how there appears to already be a passing tsd test for this behavior, will need a little more investigation!

https://github.com/fastify/fast-json-stringify/blob/74c35c0ee4c2dd12cc8edf8acad4b2f46c0542bb/types/index.test-d.ts#L153

**Comment by tmcw** [comment]
Figured that out - the type test file isn't testing for anything because all of the schemas are defined with `: Schema` as their type, which knocks out the inference. I'll rework that.
