### ISSUE TITLE
Release a new version with "merged" performance improvements 

### ISSUE THREAD

**Issue by cesco69** [fastify/fast-json-stringify#701]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

There are some performance improvements merged into the master but not released:

https://github.com/fastify/fast-json-stringify/pull/695
https://github.com/fastify/fast-json-stringify/pull/696
https://github.com/fastify/fast-json-stringify/pull/697

**Comment by cesco69** [comment]
@mcollina any news?

**Comment by mcollina** [comment]
Done
