### ISSUE TITLE
validator.js in constructor validateSchema is always false and ajvOption overriden

### ISSUE THREAD

**Issue by nullRefErr** [fastify/fast-json-stringify#720]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.26.2

### Plugin version

5.16.0

### Node.js version

18.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Sonoma 14.1

### Description

Hello, I recently did some performance tests to our application and found that schemas are compiled time to time even we compiled them at the application start up. Therefore at the begining of our performance test there is a very long schema compile time.

I found that in validator.js constructor, `validateSchema` is always `false` and `ajvOptions` is overriden.

Is this behaviour necessary or a bug ?

`validator.js`
```
  constructor (ajvOptions) {
    this.ajv = new Ajv({
      ...ajvOptions,
      strictSchema: false,
      validateSchema: false,
      allowUnionTypes: true,
      uriResolver: fastUri
    })
```
![Screenshot 2024-06-11 at 11 19 16](https://github.com/fastify/fast-json-stringify/assets/8920659/3c4529e0-432f-46c2-93c8-e467cb1ceb73)

### Link to code that reproduces the bug

https://github.dev/fastify/fast-json-stringify

### Expected Behavior

Schemas compiled once at start up.

**Comment by Eomm** [comment]
Did you solve it?
