### ISSUE TITLE
bug: array input does not work (uncaught error)

### ISSUE THREAD

**Issue by titanism** [fastify/fast-json-stringify#721]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

latest

### Plugin version

latest

### Node.js version

latest

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

latest

### Description

> JSON.stringify([{ foo: 'bar' }])
'[{"foo":"bar"}]'

> require('fast-json-stringify')([{ foo: 'bar' }])
Uncaught Error: schema is invalid: data must be object,boolean

### Expected Behavior

> JSON.stringify([{ foo: 'bar' }])
'[{"foo":"bar"}]'

> require('fast-json-stringify')([{ foo: 'bar' }])
'[{"foo":"bar"}]'

**Comment by cschloer** [comment]
Can you explain what the correct API usage is for this usecase @titanism ?
