### ISSUE TITLE
fast-json-stringify for express

### ISSUE THREAD

**Issue by nigrosimone** [fastify/fast-json-stringify#741]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi everyone,

I wanted to share something I've been working on that might be of interest to the community [express-fast-json-stringify](https://www.npmjs.com/package/express-fast-json-stringify). I've developed a library based on fast-json-stringify and integrated it with Express, inspired by its usage in Fastify.

I hope this contribution aligns with the goals of the fast-json-stringify project and proves to be useful for others. Any feedback or suggestions would be greatly appreciated!

Thank you for all your hard work on fast-json-stringify!

https://www.npmjs.com/package/express-fast-json-stringify

https://github.com/nigrosimone/express-fast-json-stringify

**Comment by mcollina** [comment]
Amazing!
