### ISSUE TITLE
Unknown format error with anyOf schemas

### ISSUE THREAD

**Issue by vserpokryl** [fastify/fast-json-stringify#747]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.1.0

### Plugin version

6.0.0

### Node.js version

22.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

15.1.1

### Description

The `fast-json-stringify` library produces an error: `unknown format "..." ignored in schema at path "#/properties/..."`. However, when a simple type (e.g., string or number) is used instead, the error is ignored.

Example:
```js
import fastJson from 'fast-json-stringify';

const stringify = fastJson({
  type: 'object',
  properties: {
    text: { type: 'string', format: 'Base64' },
    label: { anyOf: [{ type: 'number' }, { type: 'string' }] }, // Error: unknown format "Base64" ignored in schema at path "#/properties/text"
    // label: { type: 'string' }, // No errors
  },
});

console.log(stringify({ text: '', label: '' }));
```

**Comment by climba03003** [comment]
See https://github.com/fastify/fast-json-stringify?tab=readme-ov-file#anyof-and-oneof
When the schema goes through `anyOf`, `oneOf`, it is processed by `ajv` that means the schema will validate by `ajv` (error in this case).
The others part is `fast-json-stringify` and we use the schema that we understand to perform stringify (no error in this case).

I would say it is the current limitation and should always use proper json schema format.

**Comment by vserpokryl** [comment]
Thanks! I believe we should use [serializerOpts](https://fastify.dev/docs/latest/Reference/Server/#serializeropts) in our case
