### ISSUE TITLE
Support for array of types in JSON schema

### ISSUE THREAD

**Issue by florianreinhart** [fastify/fast-json-stringify#77]
The following is a valid schema, but currently unsupported by fast-json-stringify:
```json
{
    "type": "object",
    "properties": {
      "stringOrNumber": {"type": ["string", "number"], "maxLength": 10}
    }
}
```

**Comment by mcollina** [comment]
Definitely! Would you like to send a PR?

**Comment by florianreinhart** [comment]
I am already working on it.

We need to conditionally require `ajv` like it is done for `anyOf` in the `hasAnyOf` function. The hard part is to figure out if the schema includes any type arrays.
