### ISSUE TITLE
Module not found: Error: Can't resolve 'uglify-es'

### ISSUE THREAD

**Issue by manzonif** [fastify/fast-json-stringify#95]
npm doesn't reflect last uglify-es version (3.3.10). Reason: uglify-es is no longer maintained,

https://github.com/mishoo/UglifyJS2/issues/3067

**Comment by mcollina** [comment]
ouch.

What would be the fix in our case? Would you like to send a PR?

**Comment by jsumners** [comment]
It looks like we are somehow depending on a non-published version. We have 3.3.10 and the latest published is 3.3.9 -- https://www.npmjs.com/package/uglify-es

**Comment by mcollina** [comment]
Rolled back to 3.3.9.
