### ISSUE TITLE
Remove uglifier support

### ISSUE THREAD

**Issue by mcollina** [fastify/fast-json-stringify#97]
This is only relevant for Node 6 now, and I think we should drop this feature in the next major release.

**Comment by allevo** [comment]
I agree. If we add a feature like "save your stringifier function to a file". So a developer could bundle it easily

**Comment by mcollina** [comment]
@allevo what do you propose make sense. However, the uglifier was added because it improved the throughput with Crankshaft / Node 6. That has less than a year to live.
